!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 468 $
!> $Author: dsu $
!> $Date: 2017-05-01 15:53:10 -0700 (Mon, 01 May 2017) $
!> $URL: https://github.com/min3p-ubc/min3p/blob/main/src/usg/cgal_search_with_point_iface.F90 $
!---------------------------------------------------------------------
!********************************************************************!


! --------------------------------------------------------------------
!> Module of CGAL search the closest points
!>
!> Module description:
!>
!> Written by:    Danyang Su - Dec. 12, 2016
!> Last modified:
! --------------------------------------------------------------------

#ifdef CGAL

module cgal_search_with_point_iface

  !c this is feature of Fortran 2003
  use iso_c_binding

  implicit none

  private

  public cgal_search_point_initialize,     &
         cgal_search_point_add_point,      &
         cgal_search_point_make_tree,      &
         cgal_search_point_closest_point,  &
         cgal_search_point_closest_points, &
         cgal_search_point_clear_all


  !c interface binding to CGAL c++ code
  interface

    !c allocate storage for integer values
    function allocate_storage_integer(n) result(iresult) bind(C,name="allocate_storage_integer")
      import c_int, c_ptr
      implicit none
      integer(c_int),value :: n
      type(c_ptr) :: iresult
    end function allocate_storage_integer

    !c deallocate storage
    subroutine deallocate_storage(ptr) bind(C,name="deallocate_storage")
      import c_ptr
      implicit none
      type(c_ptr), intent(in), value :: ptr
    end subroutine deallocate_storage

    !c initialize
    subroutine search_point_initialize(itype) bind(C,name="search_point_initialize")
      import c_int
      implicit none
      integer(c_int), value :: itype
    end subroutine

    !c add point with id
    subroutine search_point_add_point(itype,id,x,y,z) bind(C,name="search_point_add_point")
      import c_int, c_double
      implicit none
      integer(c_int), value :: itype
      integer(c_int), value :: id
      real(c_double), value :: x,y,z
    end subroutine

    !c make data points tree
    subroutine search_point_make_tree(itype) bind(C,name="search_point_make_tree")
      import c_int
      implicit none
      integer(c_int), value :: itype
    end subroutine

    !c search closest points
    subroutine search_point_closest_point(itype,x,y,z,id) bind(C,name="search_point_closest_point")
      import c_int, c_double
      implicit none
      integer(c_int), value :: itype
      real(c_double), value :: x,y,z
      integer(c_int)  :: id
    end subroutine

    !!c search closest points
    !subroutine search_point_closest_points(itype,n,x,y,z,ipr) bind(C,name="search_point_closest_points")
    !  import c_int, c_double,c_ptr
    !  implicit none
    !  integer(c_int), value :: itype,n
    !  real(c_double), value :: x,y,z
    !  type(c_ptr) :: ipr
    !end subroutine

    !c search closest points
    subroutine search_point_closest_points(itype,n,x,y,z,ids) bind(C,name="search_point_closest_points")
      import c_int, c_double
      implicit none
      integer(c_int), value :: itype,n
      real(c_double), value :: x,y,z
      integer(c_int) :: ids(n)
    end subroutine

    !c clear data points and tree
    subroutine search_point_clear_all(itype) bind(C,name="search_point_clear_all")
      import c_int
      implicit none
      integer(c_int), value :: itype
    end subroutine

  end interface

contains

  !c initialize
  subroutine cgal_search_point_initialize(itype)
    implicit none
    integer, intent(in) :: itype
    call search_point_initialize(itype)
  end subroutine

  !c add point with id
  subroutine cgal_search_point_add_point(itype,id,x,y,z)
    implicit none
    integer, intent(in) :: itype,id
    real*8, intent(in) :: x,y,z
    call search_point_add_point(itype,id,x,y,z)
  end subroutine

  !c make data points tree
  subroutine cgal_search_point_make_tree(itype)
    implicit none
    integer, intent(in) :: itype
    call search_point_make_tree(itype)
  end subroutine

  !c search closest point
  subroutine cgal_search_point_closest_point(itype,x,y,z,id)
    implicit none
    integer, intent(in) :: itype
    real*8, intent(in) :: x,y,z
    integer :: id
    call search_point_closest_point(itype,x,y,z,id)
  end subroutine

  !c search closest points
  subroutine cgal_search_point_closest_points(itype,n,x,y,z,ids)
    implicit none
    integer, intent(in) :: itype,n
    real*8, intent(in) :: x,y,z
    integer, allocatable :: ids(:)

    !c local variables
    integer :: i
    type(c_ptr) :: ptr
    integer(c_int), dimension(:), pointer :: ids_p

    if(allocated(ids)) then
      deallocate(ids)
    end if
    allocate(ids(n))

    !!c allocate memory for the temporary indices
    !ptr = allocate_storage_integer(n)
    !call c_f_pointer(ptr,ids_p,[n])
    !call search_point_closest_points(itype,n,x,y,z,ptr)
    !do i = 1, n
    !  ids(i) = ids_p(i)
    !end do
    !!c release memory
    !call deallocate_storage(ptr)

    call search_point_closest_points(itype,n,x,y,z,ids(1:n))

    return

  end subroutine

  !c clear data points and tree
  subroutine cgal_search_point_clear_all(itype)
    implicit none
    integer, intent(in) :: itype
    call search_point_clear_all(itype)
  end subroutine

end module cgal_search_with_point_iface

#endif
