!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 826 $
!> $Author: dsu $
!> $Date: 2022-03-24 10:10:16 -0700 (Thu, 24 Mar 2022) $
!> $URL: https://min3psvn.ubc.ca/svn/min3p_thcm/branches/dsu_new_add_2024Jan/src/usg/infcrt_mcd_usg.F90 $
!---------------------------------------------------------------------
!********************************************************************!

    
!c --------------------------------------------------------------------------
!c subroutine infcrt_mcd
!c -------------------
!c 
!c compute influence coefficients for diffusive flux terms 
!c for rectangular, cartesian finite volume discretization
!c (reactive transport)
!c 
!c This function is deprecated due to the update in infcrt_mcd.F90 in Sept 2021.
!c 
!c written by:      Danyang Su - Aug 04, 2016
!c
!c last modified:
!c                  Danyang Su - Sept 14, 2021
!c 
!c definition of variables:
!c 
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                        I O
!c     input:
!c 
!c        idbg - output for debugging information
!c        ilog - unit number, logbook
!c        nngl - max cells for dim purposes (ncomp.com)
!c        nphas - max number of phases (ncomp.com)
!c        njavs - max dim javs array (ncomp.com)
!c        nx, ny, nz - number of cells in x,y,z dir
!c        pornew(ibk) - porosity
!c        sanew(nngl) - aqueous phase saturation
!c        iavs(), javs() - ysmp pointers
!c        isymvs(ii) - symmetry pointer for cell ibk
!c        tortuosity_corr    = .true.  -> Millington-Quirk
!c                                         tortuosity correction
!c                                         for diffusion
!c                                         coefficients
!c 
!c 

!c     output:
!c 
!c        cinfrt_mcd() - area / dx * saturation * porosity 
!c                      influence coefficients
!c        deltaij     - distance between i and j [m]
!c        tauij       - tortusosity correction for gas diffusion 
!c        porij       - water filled porosity at interface i-j
!c        satij       - water saturation at interface i-j
!c 
!c passed:   -
!c 
!c common:   -
!c 
!c local:
!c 
!c external: 
!c           
!c --------------------------------------------------------------------------
#ifdef USG
      subroutine infcrt_mcd_usg
#ifdef OPENMP
      use omp_lib 
#endif
      use gen, only :                                                  &
#ifdef OPENMP
                      numofthreads_global,                             &
                      numofloops_thred_global,                         &
                      numofloops_thred_infcrt_mcd_1,                   &
                      numofloops_thred_infcrt_mcd_2,                   &
#endif
                      iavs, javs, isymvs, pornew, sanew, njavs, nngl,  &
                      tortuosity_corr, deltaij, tauij, porij,satij,    &
                      assigned_tau, tau, type_tortuosity,marchies,     &
                      cinfrad, radial_coord, multi_diff, tau_fac,      &
                      sonew, jaedgelen, tor_corr_a_mq, tor_corr_b_mq,  &
                      jacell, janumcell, jaedgeunitdirection,          &
                      mpropvs, useAnisoTauCorr, type_averaging_De,     &
                      idbg, ilog, rank, b_enable_output

      use multidiff, only : cinfrt_mcd, multi_diff
      use mod_diffcoff, only : diffcoff
      use phys, only : atc_zone, aca_vol

      use geometry
      use usg_mesh_data, only : nodes, cells, cell_type, cvol_method,  &
                                num_edge_dvols, num_edge_maxcells,     &
                                num_nodes_per_cell,                    &
                                cell_projection, CellCvolFaceArea,     &
                                CellCvolFaceUnitNorm,                  &
                                CellCvolFace_disp_mcd,                 &
                                CellCvolFace_disp_mcd_tensor,          &
                                get_cell_edge_cvol_id
#ifdef PETSC
      use petsc_mpi_common, only : petsc_mpi_finalize
#endif

      implicit none
      
!c    local variables
      integer :: ivol, jvol, istart, iend, idvol, idvol_r, icell,      &
                 icell2, iedge_r, izn, jzn, jtemp, ii, info_debug
      real*8, parameter :: r0 = 0.0d0, r1 = 1.0d0, rhalf = 0.5d0,      &
              rsmallarea = 1.0d-8, pi = 3.141592653589793d0

      real*8 :: tauloc, porav, satav, diffav, diff_eff,                &
                so_av, marchieav, tort, cvolfacearea, rswitch

      type(tensor) :: rml, rmr, diff_eff_tensor

      type(point) :: tend, wtend, utend, vtend, ntend, atc_av, aca_av

      real*8 :: diff_eff_direct, diff_eff_cross, alpha, beta


!c  compute influence coefficients for diffusive flux terms
!c  in gas phase


!c  loop over control volumes
#ifdef OPENMP
    !$omp parallel                                                    &
    !$omp if (nngl > numofloops_thred_infcrt_mcd_2)                   &
    !$omp num_threads(numofthreads_global)                            &
    !$omp default(shared)                                             &
    !$omp private (ivol, istart, iend, icell, icell2,                 &
    !$omp idvol, idvol_r, iedge_r, izn, jzn, jtemp, jvol,             &
    !$omp tend, ntend, wtend, utend, vtend,                           &
    !$omp cvolfacearea, diffav, diff_eff, marchieav, porav,           &
    !$omp rswitch, satav, so_av, tauloc, tort, aca_av, atc_av,        &
    !$omp rml, rmr, diff_eff_tensor)                                                 
    !$omp do schedule(static)
#endif
      do ivol = 1, nngl

        istart = iavs(ivol)+1
        iend = iavs(ivol+1)-1
        do jtemp = istart, iend  !c loop over connection
          jvol = javs(jtemp)
!c average porosity of the element, can be other interpolation methods
          porav = 0.5d0*(min(r1, pornew(ivol)) + min(r1,pornew(jvol)))

!c  average tortuosity of the element
          if (assigned_tau) then
            tauloc = 0.5d0*(tau(ivol)*tau_fac(ivol) +                  &
                           tau(jvol)*tau_fac(jvol))
          end if

!c  calculate the diffusion tensor for the "pseudo diffusion element"
!c  average porosity of the element
          satav = (min(r1,sanew(ivol))+min(r1,sanew(jvol)))*0.5d0
          so_av = (min(r1,sonew(ivol))+min(r1,sonew(jvol)))*0.5d0

!c  calculate the average marchie factor
          marchieav = (marchies(ivol)+marchies(jvol))*0.5d0

!c  calculate effective diffusion coefficient
          diffav = r1
          diff_eff = diffcoff(diffav,satav,porav,tortuosity_corr,      &
                              assigned_tau,tauloc,type_tortuosity,     &
                              marchieav,so_av,                         &
                              tor_corr_a_mq,tor_corr_b_mq)

          !cdsu get rotation angle for anisotropic tortuosity and dispersivity correction
          if (useAnisoTauCorr) then
            izn = mpropvs(ivol)
            jzn = mpropvs(jvol)
            
            aca_av = (aca_vol(ivol) + aca_vol(jvol))*rhalf
            call geometry_cal_rotation_matrix(aca_av,rml,rmr)

            if (type_averaging_De .eq. 'harmonic') then
              atc_av = math_common_harmonic(atc_zone(izn),atc_zone(jzn))
            else
              atc_av = (atc_zone(izn) + atc_zone(jzn))*rhalf
            end if

            diff_eff_tensor = tensor_zero
            diff_eff_tensor%xx = r1*atc_av%x
            diff_eff_tensor%yy = r1*atc_av%y
            diff_eff_tensor%zz = r1*atc_av%z

            diff_eff_tensor = (rml.dot.diff_eff_tensor).dot.rmr

          else
            !c to be further checked, tend is set to one for Multi-Diff
            tend = math_common_set_vector(r1,r1,r1)
          end if

          !c  added for Multi-Diff
          tort = diff_eff / diffav / porav      ! tortuosity

          !c influence coefficient of direct gradient term
          do icell = 1, janumcell(jtemp)  !c loop over all linked cells
            icell2 = jacell(icell,jtemp)
            if (icell2 <= 0) then
              cycle
            end if
            do idvol = 1, num_edge_dvols   !c loop over all dual volumes
              call get_cell_edge_cvol_id(idvol,ivol,jvol,icell2,       &
                                         idvol_r,iedge_r,rswitch)
              cvolfacearea = CellCvolFaceArea(idvol_r,iedge_r,icell2)
              if(jacell(icell,jtemp) > 0 .and. cvolfacearea > rsmallarea) then

                !c save multicomponent diffusion tensor

                if (rswitch > r0) then
                  if (useAnisoTauCorr) then
                    CellCvolFace_disp_mcd_tensor(idvol_r,iedge_r,icell2) = diff_eff_tensor
                  else
                    CellCvolFace_disp_mcd(idvol_r,iedge_r,icell2) = tend
                  end if
                end if

              end if
            end do
          end do

          deltaij(jtemp)          = jaedgelen(jtemp)
          !deltaij(isymvs(jtemp))  = jaedgelen(jtemp)
          porij(jtemp)            = porav
          !porij(isymvs(jtemp))    = porav
          tauij(jtemp)            = tort
          !tauij(isymvs(jtemp))    = tort
          satij(jtemp)            = satav
          !satij(isymvs(jtemp))    = satav
        end do
      end do
#ifdef OPENMP
    !$omp end do
    !$omp end parallel
#endif 

#ifdef DEBUG
      info_debug = 0
      if (info_debug.gt.0) then
      
      do ivol = 1,nngl
        do ii = iavs(ivol),iavs(ivol+1)-1
          write(idbg,'(a,i4,a,es12.3,/)')                              &                       !Previous format '(a,i4,a,es12.3)/' is not correct. The extra characters "/" in the format specification will be ignored.
                'cinfrt_mcd(',ii,') = ',cinfrt_mcd(ii)
        end do
      end do
      
      do ivol = 1,nngl
        do ii = iavs(ivol),iavs(ivol+1)-1
          write(idbg,'(a,i4,a,es12.3,/)')                              &
                'deltaij(',ii,') = ',deltaij(ii)
        end do
      end do

      do ivol = 1,nngl
        do ii = iavs(ivol),iavs(ivol+1)-1
          write(idbg,'(a,i4,a,es10.3,/)')                              &
                'porij(',ii,') = ',porij(ii)
        end do
      end do

      do ivol = 1,nngl
        do ii = iavs(ivol),iavs(ivol+1)-1
          write(idbg,'(a,i4,a,es10.3,/)')                              &
                'tauij(',ii,') = ',tauij(ii)
        end do
      end do
      
      write(idbg,*) 'wrote to dbg from infcrt_mcd.f'

      end if !(info_debug.gt.0)
#endif


      return
      end
#endif
