!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 826 $
!> $Author: dsu $
!> $Date: 2022-03-24 10:10:16 -0700 (Thu, 24 Mar 2022) $
!> $URL: https://min3psvn.ubc.ca/svn/min3p_thcm/branches/dsu_new_add_2024Jan/src/min3p/dtotdyvisc.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c  ----------------------------------------------------------------------
!c  subroutine dtotdyvisc
!c  -------------------
!c 
!c  compute derivatives of total aqueous component dynamic viscosity based 
!c  on concentrations of free species and secondary aqueous species
!c 
!c  written by:      Pejman Rasouli - February 24, 2010
!c 
!c  last modified:   
!c 
!c                   Danyang Su - Sept 29, 2021
!c                   Deprecated 
!c
!c  definition of variables:
!c 
!c  I --> on input   * arbitrary  - initialized  + entries expected
!c  O --> on output  * arbitrary  - unaltered    + altered
!c                                                                     I O
!c  passed:   real*8:
!c            -------
!c            c(nc)              = concentrations of free species      + -
!c                                 - new time level [moles/l water]
!c            cx(nx)             = concentrations of secondary         + -
!c                                 aqueous species
!c                                 - new time level [moles/l water]
!c            drtinc             = increment for numerical             + -
!c                                 differentiation
!c 
!c            integer*4:
!c            ----------
!c            jbl                = pointer to column of block matrix   + -
!c 
!c  chem.f:   real*8:
!c            -------
!c            cxinc(nx,nthreads) = secondary aqueous species           + -
!c                                 concentrations dependent on
!c                                 incremented free species
!c                                 concentrations
!c                                 [moles/l water]
!c            dtotc(n,nthreads)  = derivatives of total aqueous        * +
!c                                 component concentrations
!c                                 [moles/l water]
!c            xnux(nx*nc)        = stoichiometric coefficient matrix   + -
!c                                 for formation of secondary aqueous
!c                                 species from free species
!c 
!c            integer*4:
!c            ----------
!c            iax(nx+1)          = row pointer array to                + -
!c                                 stoichiometric coefficients of
!c                                 free species in
!c                                 secondary aqueous species
!c            jax(nx*nc)         = column pointer array to             + -
!c                                 stoichiometric coefficients of
!c                                 free species in secondary aqueous
!c                                 species
!c            nc                 = number of components                + -
!c            nx                 = number of secondary aqueous         + -
!c                                 species
!c 
!c 
!c  local:    integer*4:
!c            ----------
!c            i                   = counter (stoichiometric
!c                                  coefficients)
!c            ibl                 = counter (components)
!c            ibl2                = counter (components)
!c            istart              = pointer (stoichiometric 
!c                                  coefficients)
!c            istop               = pointer (stoichiometric
!c                                  coefficients)
!c            ix                  = counter (secondary species) 
!c 
!c  external: -
!c  ----------------------------------------------------------------------
  
      subroutine dtotdyvisc(cd_ivol,cdx_ivol,cd_jvol,cdx_jvol,         &
                            diff_cof_ic_ivol,diff_cof_ix_ivol,         &
                            diff_cof_ic_jvol,diff_cof_ix_jvol,         &
                            type_ave_De,drtinc,tid)
     
      use parm
      use chem
      use gen
 
      implicit none      
     
      integer :: tid
       
      real*8 :: drtinc,cd_ivol(nc),cdx_ivol(nx),                       &
                cd_jvol(nc),cdx_jvol(nx),                              &
                diff_cof_ic_ivol(nc),diff_cof_ix_ivol(nx),             &
                diff_cof_ic_jvol(nc),diff_cof_ix_jvol(nx)
      character(len=*) :: type_ave_De          
      
!c local variables 
      real*8 :: diff_ij     
      real*8 :: diff_cof_ic(nc),diff_cof_ix(nx)      
      integer :: i, ic, ibl, info_debug, ix, istart, istop 
      real*8 :: r0 = 0.0d0, r1 = 1.0d0, r2 = 2.0d0, rhalf = 0.5d0

!c apply averaging method
      diff_cof_ic = r0
      diff_cof_ix = r0

      if (type_ave_De.eq.'harmonic') then
        do ic=1,nc          ! loop over free species 
          diff_ij = diff_cof_ic_ivol(ic)*diff_cof_ic_jvol(ic)
          if (diff_ij > r0) then
            diff_cof_ic(ic) = r2*diff_ij/(diff_cof_ic_ivol(ic)+        &
                                          diff_cof_ic_jvol(ic))
          end if          
        end do

        do ix=1,nx          ! loop over secondary species 
          diff_ij = diff_cof_ix_ivol(ix)*diff_cof_ix_jvol(ix)
          if (diff_ij > r0) then
            diff_cof_ix(ix) = r2*diff_ij/(diff_cof_ix_ivol(ix)+        &
                                          diff_cof_ix_jvol(ix))
          end if          
        end do
      else if (type_ave_De.eq.'arithmetic') then
        do ic=1,nc          ! loop over free species 
          diff_cof_ic(ic) = rhalf*(diff_cof_ic_ivol(ic)+               &
                                   diff_cof_ic_jvol(ic))
        end do

        do ix=1,nx            ! loop over secondary species 
          diff_cof_ix(ix) = rhalf*(diff_cof_ix_ivol(ix)+               &
                                   diff_cof_ix_jvol(ix))
        end do
      else if (type_ave_De.eq.'no averaging') then
        do ic=1,nc          ! loop over free species 
          diff_cof_ic(ic) = diff_cof_ic_ivol(ic)
        end do

        do ix=1,nx            ! loop over secondary species 
          diff_cof_ix(ix) = diff_cof_ix_ivol(ix)
        end do
      end if            
     
!c   contributions from free species 
 
      do ibl=1,nc-1
      
        dtotviscnew(ibl,tid) = diff_cof_ic(ibl)*                       &
                               (cd_jvol(ibl) - cd_ivol(ibl))
        
      end do
 
!c   sum up contributions from aqueous complexes
 
      do ix=1,nx
        istart = iax(ix)
        istop = iax(ix+1)-1
        do i = istart,istop
          ibl = jax(i)

!c   skip h2o, since not a primary unknown
 
          if (namec(ibl).ne.'h2o') then
          
            dtotviscnew(ibl,tid) = dtotviscnew(ibl,tid) +              &
                                   diff_cof_ix(ix) *                   &
                                   (xnux(i)*(cdx_jvol(ix)-cdx_ivol(ix)))
          
          end if
        end do
      end do
 
!c   form derivative -> divide by increment for numerical
!c   differentiation
 
      do ibl=1,nc-1
      
        dtotviscnew(ibl,tid) = dtotviscnew(ibl,tid)/drtinc
        
      end do
 
!cdbg
#ifdef DEBUG
      info_debug = 0
      if (info_debug.gt.0) then
         do ic=1,nc-1     
             write(idbg,'(a,i4,a,1pe15.6e3,/)')                        &
     &          'dtotvisc(',ic,') = ',dtotviscnew(ic,tid)   
         end do
         write(idbg,'(a,1pe15.6e3,/)') 'time = ',time
      end if
#endif
!cdbg
 
      return
      end
