!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 221 $
!> $Author: dsu $
!> $Date: 2014-08-05 14:29:49 -0700 (Tue, 05 Aug 2014) $
!> $URL: https://min3psvn.ubc.ca/svn/min3p_thcm/branches/dsu_new_add_2024Jan/src/min3p/dtotcong.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine dtotcong
!c -------------------
!c
!c compute numerical derivatives of total gaseous component 
!c concentrations based on concentrations of gaseous species
!c (incremented - not incremented)
!c
!c written by:      Uli Mayer - December 30, 96
!c
!c last modified:   -   
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           g(ng)              = concentrations of gaseous species   + -
!c                                [moles/l water]
!c           ginc(ng,nthreads)  = concentrations of gaseous species   + -
!c                                - incremented [moles/l water]
!c           drtinc             = increment for numerical             + -
!c                                differentiation
!c           dtotg(n)           = derivatives of total gaseous        * +
!c                                component concentrations
!c                                [moles/l water]
!c           xnug(ng*nc)        = stoichiometric coefficient matrix   + -
!c                                for formation of gaseous species  
!c                                from components
!c
!c           integer*4:
!c           ----------
!c           iaga(ng+1)         = row pointer array to                + -
!c                                stoichiometric coefficients of
!c                                components in gaseous species
!c           jbl                = pointer to column of block matrix   + -
!c           jaga(ng*nc)        = column pointer array to             + -
!c                                stoichiometric coefficients of
!c                                components in gaseous 
!c                                species
!c           nc                 = number of components                + -
!c           ng                 = number of gases                     + -
!c
!c           character:
!c           ----------
!c           namec(nc)          = component names                     + -
!c
!c local:    integer*4:
!c           ----------
!c           ig                  = counter (gases) 
!c           ibl                 = counter (rows of block matrix)
!c           istart              = pointer (stoichiometric 
!c                                 coefficients)
!c           iend                = pointer (stoichiometric
!c                                 coefficients)
!c           i                   = counter (stoichiometric
!c                                 coefficients)
!c
!c external: -
!c ----------------------------------------------------------------------
  
      subroutine dtotcong(g,ginc,dtotg,xnug,drtinc,   &
                         iaga,jaga,nc,ng,jbl,namec)
      
      implicit none
 
 
      character*72 :: namec
      integer :: nc, ng, jbl
      real*8 :: drtinc
      real*8 :: g, ginc, dtotg, xnug
      integer :: iaga, jaga
      dimension :: g(*),ginc(*),dtotg(*),xnug(*),iaga(*),jaga(*),namec(*)
      
      !local variable
      real*8 :: r0
      integer :: i, ibl, ig, istart, iend
 
      parameter (r0 = 0.0d0)
 
!c  zero array

      do ibl = 1,nc-1
        dtotg(ibl) = r0
      end do
 
!c  gaseous species
 
      do ig=1,ng
        istart = iaga(ig)
        iend = iaga(ig+1)-1
        do i = istart,iend
          ibl = jaga(i)
 
!c  skip h2o, since not a primary unknown
 
          if (namec(ibl).ne.'h2o') then
            dtotg(ibl) = dtotg(ibl) + xnug(i)*(ginc(ig)-g(ig))
          end if
        end do
      end do
 
!c  form derivative -> divide by increment for numerical
!c  differentiation
 
      do ibl=1,nc-1
        dtotg(ibl) = dtotg(ibl)/drtinc
      end do
 
      return
      end
