!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 880 $
!> $Author: dsu $
!> $Date: 2024-02-19 14:19:39 -0800 (Mon, 19 Feb 2024) $
!> $URL: https://min3psvn.ubc.ca/svn/min3p_thcm/branches/dsu_new_add_2024Jan/src/min3p/initcpgb.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine initcpgb
!c -------------------
!c
!c control parameters for gas bubbles
!c
!c written by:      Rich Amos - April 10, 2004
!c
!c last modified:   
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c 
!c                                                                    I O
!c passed:   -
!c
!c common:   
!c gen.f:    real*8:
!c           -------
!c
!c
!c           integer*4:
!c           ----------
!c           idat               = unit number, run specific input     + -
!c                                             file
!c           itmp               = unit number, temporary storage 
!c           igen               = unit number, generic output file    + -
!c           ilog               = unit number, log book               + -
!c
!c           character:
!c           ----------
!c           section_header     = section header
!c 
!c chem.f:   real*8:
!c           -------
!c           pres_atm           = atmospheric pressure [atm]
!c
!c
!c bbls.f:      real*8:
!c           -------
!c           bubreact_tol            = convergance tolerance for inner bubble loop
!c           bubflow_tol             = convergance tolerance for outer bubble loop
!c           maxsg_update            = maximum update in gas saturation per loop
!c           gas_tol                 = convergance tolerance for bubble newton loop
!c           res_tol                 = residual tolerance for bubble newton loop
!c           
!c           integer*4
!c           ---------
!c           maxibub                 = maximum number of inner bubble iterations
!c           maxibubflow             = maximum number of outer bubble iterations
!c
!c           logical
!c           --------
!c           double_bubble           = .true. -> double bubble iterations
!c           bubble_out              = .true. -> write bubble output file
!c           bubble_perm             = .true. -> update permeability due to change in gas 
!c                                         saturation
!c
!c local:    integer*4:
!c           ----------
!c           l_string           = length of text string
!c
!c           logical:
!c           --------
!c           found_section      = .true.  -> section header was
!c                                           found in input file
!c           found_subsection   = .true.  -> subsection header was
!c                                           found in input file
!c
!c           character:
!c           ----------
!c           subsection         = name of subsection in input file
!c
!c external: findstrg  = find text string in file
!c           readbloc  = read section of input file and write to 
!c                       temporary file
!c ----------------------------------------------------------------------
 
      subroutine initcpgb
 
      use parm
      use gen
      use chem
      use dual
      use bbls
#ifdef PETSC
      use petsc_mpi_common, only : petsc_mpi_finalize
#endif

      implicit none

      external findstrg, readbloc

      real, parameter :: r86400 = 8.64d4
      integer :: i, l_string, ierrcd
      logical found_section, found_subsection
      character*72 subsection
 
!c  read control parameters for reactive transport
!c  and write to temporary file

      ierrcd = 0
   
      section_header = 'control parameters - bubble model'
      call readbloc (idat,itmp,section_header,found_section,.true.)

!c  define length of section header

      l_string = index(section_header,'  ')-1
      if (l_string.eq.-1.or.l_string.gt.72) then
         l_string=72
      end if

!c  define defaults for control parameters for reactive transport

!c  general control parameters

      double_bubble = .false.
      bubble_out = .false.
      bubble_perm = .false.
      pres_atm = 1.0d0
      zero_storage = .false.


!c  bubble iterations

      maxibub = 100
      maxibubflow = 100
      bub_exp = 20
      bubreact_tol = 1.0d-7
      bubflow_tol = 1.0d-7
      maxsg_update = 1.0d-3
      dsadt_max = 1.0d10
      ts_lim = 0.001
      bub_sgmin = 1.0d-10
      sg_count_max = 10000

!c  Newton iteration

      gas_tol = 1.0d-12
      res_tol = 1.0d-12

!c  read in control parameters for bubble model

      if (found_section) then


!c  general control parameters

!c  double iterations

        subsection = 'double bubble'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          double_bubble = .true.
        end if

!c  write bubble output file

        subsection = 'output bubble info'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          bubble_out = .true.
        end if

!c  update permeability based on gas saturation

        subsection = 'permeability update_bubbles'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          bubble_perm = .true.
        end if

!c  use zero gas phase storage approximation

        subsection = 'zero gas phase storage'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          zero_storage = .true.
        end if

!c read atmospheric pressure from input file

        subsection = 'atmospheric pressure'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          ierrcd = 1
          read(itmp,*,err=999,end=999) pres_atm
        end if

!c  settings for bubble iterations

        subsection = 'bubble iteration settings'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          ierrcd = 2
          read(itmp,*,err=999,end=999) maxibub
          read(itmp,*,err=999,end=999) maxibubflow
          read(itmp,*,err=999,end=999) bub_exp
          read(itmp,*,err=999,end=999) bubreact_tol 
          read(itmp,*,err=999,end=999) bubflow_tol
          read(itmp,*,err=999,end=999) maxsg_update
          read(itmp,*,err=999,end=999) dsadt_max          
          !c note: the parameter dsadt_max is not read  
          !c in the original ebullition code. The definition or value
          !c of the dsadt_max is not consistent with that specified 
          !c in the input file. For Cirkpa case, a very large value 1.0d10 is used
          !c while for the other cases, a small value 1.0d-3 is used.
          !c New format of 'bubble iteration settings' is required. DSU, 2020-04-22

          if (maxibub < 1 .or. maxibubflow < 1) then
            if (rank == 0 .and. b_enable_output) then
              write(*,'(a)') 'error in the number of bubble iterations, value < 1'
              write(ilog,'(a)') 'error in the number of bubble iterations, value < 1'
            end if
            ierrcd = 3
            goto 999
          end if
        end if

!c  settings for Newton iteration

        subsection = 'newton iteration settings'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          ierrcd = 4
          read(itmp,*,err=999,end=999) gas_tol
          read(itmp,*,err=999,end=999) res_tol 
        end if

!c  settings for updated bubble iteration to fix bug and improve efficiency, added by DSU, 2024-02-17

        subsection = 'updated bubble iteration settings'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          ierrcd = 2
          read(itmp,*,err=999,end=999) maxibub
          read(itmp,*,err=999,end=999) maxibubflow
          read(itmp,*,err=999,end=999) bub_exp
          read(itmp,*,err=999,end=999) maxsg_update
          read(itmp,*,err=999,end=999) dsadt_max          

          if (maxibub < 1 .or. maxibubflow < 1) then
            if (rank == 0 .and. b_enable_output) then
              write(*,'(a)') 'error in the number of bubble iterations, value < 1'
              write(ilog,'(a)') 'error in the number of bubble iterations, value < 1'
            end if
            ierrcd = 3
            goto 999
          end if
        end if

!c  settings for updated Newton iteration, added by DSU, 2024-02-17

        subsection = 'updated newton iteration settings'

        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          ierrcd = 4
          read(itmp,*,err=999,end=999) sg_count_max
          read(itmp,*,err=999,end=999) gas_tol
          read(itmp,*,err=999,end=999) res_tol
        end if

      end if                 !(found_section)
      
!c  settings for Newton iteration

      subsection = 'limit timestep reduction at targets'

      call findstrg(subsection,itmp,found_subsection)

      if (found_subsection) then
        ierrcd = 5
        read(itmp,*,err=999,end=999) ts_lim 
      end if                 !(found_section)

!c  write control parameters for reactive transport
!c  to generic output file
      if (rank == 0 .and. b_enable_output) then
          
        write(igen,'(/72a)')('-',i=1,72)
        write(igen,'(a)') section_header(:l_string)
        write(igen,'(72a/)')('-',i=1,72)

!c  general control parameters

        if (double_bubble) then
          write(igen,'(a)') 'double bubble iterations'
        else
          write(igen,'(a)') 'single bubble iteration'
        end if
        if (bubble_perm) then
          write(igen,'(a)') 'permeability update based on gas saturation'
        end if
        if (zero_storage) then
          write(igen,'(a)') 'zero gas phase storage approximation'
        end if
       
        write(igen,'(a,1pe15.6e3)') 'atmospheric pressure     = ',pres_atm
      
!c  bubble model iteration

        write(igen,'(a,i10)')                                          &
             'maximum number of inner bubble iterations       = ',     &
             maxibub      
        write(igen,'(a,i10)')                                          &
             'maximum number of outer bubble iterations       = ',     &
             maxibubflow  
        write(igen,'(a,1pe15.6e3)')                                    &
             'convergance tolerance for inner bubble loop     = ',     &
             bubreact_tol      
        write(igen,'(a,1pe15.6e3)')                                    &
             'convergance tolerance for outer bubble loop     = ',     &
             bubflow_tol  
        write(igen,'(a,1pe15.6e3)')                                    &
             'maximum increase in gas satuartion per loop     = ',     &
             maxsg_update
        
!c  Newton iteration

        write(igen,'(a,1pe15.6e3)')                                    &
            'convergance tolerance for newton iterations     = ',gas_tol
        write(igen,'(a,1pe15.6e3)')                                    &
            'residual tolerance for newton iterations        = ',res_tol
        
      end if

      goto 1000

999   continue
      if (rank == 0) then
        write(ilog,'(a)') 'error reading input file, error code ', ierrcd
        write(ilog,'(a)') 'section "',section_header(:l_string),'"'
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop

1000  return
      end
