!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 786 $
!> $Author: dsu $
!> $Date: 2021-01-06 21:41:32 -0800 (Wed, 06 Jan 2021) $
!> $URL: https://min3psvn.ubc.ca/svn/min3p_thcm/branches/dsu_new_add_2024Jan/src/min3p/mem_ntmp.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c -----------------------------------------------------------------------
!c subroutine mem_ntmp
!c -------------------
!c
!c allocate memory for one-dimensional arrays of size ntmp and 
!c related arrays
!c
!c written by:      Uli Mayer - January 10, 2000
!c
!c last modified:   -
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   -
!c
!c common:
!c gen.f:    integer:
!c           --------
!c           ilog               = unit number, logbook file           + -
!c
!c chem.f:   real*8:
!c           -------
!c           tmp(ntmp)          = specified depth dependent           * +
!c                                temperatures [K]
!c           ztmp(ntmp)         = depths of specified temperatures    * +
!c
!c           integer:
!c           --------
!c           ntmp               = number of temperature points
!c
!c local:    integer:
!c           --------
!c           ierr               = 0 -> memory allocation successful
!c
!c external: checkerr  = check for error during memory allocation
!c
!c---------------------------------------------------------------------- 
!c WARNING
!c---------------------------------------------------------------------- 
!c All allocated variables are initialized to some value. This depends  
!c of its type:
!c 
!c real*8      => 0.0d0
!c integer     => 0 
!c character   => ' '    
!c logical     => .false. 
!c 
!c Sergio Andres Bea Jofre (2009)
!c
!c ----------------------------------------------------------------------
  
      subroutine mem_ntmp
 
      use parm
      use gen
      use chem
      
      implicit none
      
      integer :: ierr
 
      external checkerr

      allocate (tmp(ntmp), stat = ierr)
      tmp=0.0d0 
      call checkerr(ierr,'tmp',ilog)
      call memory_monitor(sizeof(tmp),'tmp',.true.)

      allocate (ztmp(ntmp), stat = ierr)
      ztmp=0.0d0 
      call checkerr(ierr,'ztmp',ilog)
      call memory_monitor(sizeof(ztmp),'ztmp',.true.)

      return
      end
