!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 826 $
!> $Author: dsu $
!> $Date: 2022-03-24 10:10:16 -0700 (Thu, 24 Mar 2022) $
!> $URL: https://min3psvn.ubc.ca/svn/min3p_thcm/branches/dsu_new_add_2024Jan/src/min3p/opnenergybal.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine opnenergybal
!c -------------------
!c
!c open mass balance files 
!c
!c written by:      Sergio Andres Bea Jofre 
!c
!c 
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c 
!c                                                                    I O
!c passed:   -   
!c
!c common:   
!c gen.f:    integer*4:
!c           ----------
!c           icnv               = unit number, data conversion        + -
!c           ifls               = unit number, file information       + -
!c           imrt               = unit number, mass balance -         * *
!c                                             reactive transport
!c           imrt_first         = pointer - first unit number for     * +
!c                                mass balance - reactive transport
!c           imrt_last          = pointer - last unit number for      * +
!c                                mass balance - reactive transport
!c           imvs               = unit number, mass balance -         * *
!c                                             variably saturated
!c                                             flow
!c           imvs_first         = pointer - first unit number for     * +
!c                                mass balance - variably saturated
!c                                               flow
!c           imvs_last          = pointer - last unit number for      * +
!c                                mass balance - variably saturated
!c                                               flow
!c           l_prfx             = length of prefix of I/O files       + -
!c           nmb                = number of mass balance files for    + -
!c                                selected species
!c
!c           logical:
!c           --------
!c           mass_balance_rt    = .true.  -> compute mass balance     + -
!c                                           (reactive tramsport)
!c           mass_balance_vs    = .true.  -> compute mass balance     + -
!c                                           (variably saturated 
!c                                            flow)
!c
!c           character:
!c           ----------
!c           namemb(nmb)        = names of selected species           + -
!c           prefix             = prefix name for all I/O files       + -
!c           time_unit          = time unit for output -> 'years'     + -
!c                                                        'days'
!c
!c chem.f:   integer*4:
!c           ----------
!c           iaic(nsites)       = pointer array for compressed        + -
!c                                storage of surface site data
!c           nanc               = number of sorbed species            + -
!c           naq                = number of intra-aqueous kinetic     + -
!c                                reactions
!c           nc                 = number of components including h2o  + -
!c           nm                 = number of minerals                  + -
!c           ng                 = number of gases                     + -
!c           nsb                = number of sorbed species            + -
!c           nsb_ion            = number of sorbed species            + -
!c                                (ion-exchange)
!c           nsb_surf           = number of sorbed species            + -
!c                                (surface-complex)
!c           nsites             = number of surface sites             + -
!c
!c           character:
!c           ----------
!c           isotherm_type(nc)  = definition of sorption isotherm     + -    
!c                                'none' = no sorption
!c                                'linear' = linear adsorption
!c                                'freundlich' = Freundlich isotherm
!c                                'langmuir' = Langmuir isotherm
!c           nameanc(nc)        = names of sorbed species             + -
!c                                (non-competitive sorption)
!c           nameaq(naq)        = names of intra-aqueous kinetic      + -
!c                                reactions
!c           namec(nc)          = component names                     + -
!c           nameg(ng)          = names of gases                      + -
!c           namem(nm)          = mineral names                       + -
!c           namesb(nsb)        = names of sorbed species             + -
!c           namesb_ion(nsb_ion)= names of sorbed species             + -
!c                                (ion-exchange)
!c           namesb_surf(nsb_surf)= names of sorbed species           + -
!c                                  (surface-complex)
!c
!c           logical:
!c           --------
!c           noncompetitive_sorption = logical array for activation   + -  
!c                                     of noncompetitive sorption
!c                                     reactions
!c
!c local:    integer*4:
!c           ----------
!c           ianc               = counter (non-competitive sorption
!c                                         reactions)
!c           iaq                = counter (intra-aqueous kinetic 
!c                                         reactions)
!c           ic                 = counter (components)
!c           ig                 = counter (gases)
!c           im                 = counter (minerals)
!c           imb                = counter (selected species)
!c           isb                = counter (sorbed species)
!c           isites             = counter (surface sites)
!c           l_sufx             = length of file suffix
!c
!c           character:
!c           ----------
!c           suffix             = file suffix
!c
!c external: -
!c ----------------------------------------------------------------------
 
      subroutine opnenergybal

#ifdef PETSC
#include <petscversion.h>
#if (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR >= 8)
#include <petsc/finclude/petscsys.h>
      use petscsys
#endif
#endif

      use parm
      use gen
      use chem
      use file_unit, only : lun_get, lun_set
      use file_utility, only : check_rewind_status
      use module_binary_mpiio, only : binary_file_open,               &
                                       tecplot_binary_write_header,    &
                                       tecplot_binary_write_variable,  &
                                       tecplot_binary_write_zoneinfo,  &
                                       tecplot_binary_write_section

      implicit none
#ifdef PETSC
#if (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR >= 6 && PETSC_VERSION_MINOR < 8)
#include <petsc/finclude/petscsys.h>
#elif (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR < 6)
#include <finclude/petscsys.h>
#endif
#endif
      
      integer :: i, ierr

      character*2 suffix
      
      character*75 :: tec_variables(100)      
      integer :: nvarsimheat
      character*2048 :: strbuffer
      logical :: b_rewind_valid

      external :: checkerr

      b_rewind_valid = .false.

      !imheat_first  = 55
      imheat_first  = lun_get()
      call lun_set(imheat_first+1)
      call lun_set(imheat_first+2)
      

      if (rank == 0 .and. b_enable_output) then
        write(ifls,'(//72a/a/72a/)')      &
     &       ('*',i=1,72),                &
     &       'energy balance',            &
     &       ('*',i=1,72)
      end if  

!c  system energy

      imheat = imheat_first
        
      if (rank == 0 .and. b_enable_output .and. b_output_trans_binary) then
        allocate(imheat_mpi(imheat_first:imheat_first+2), stat = ierr)
        call checkerr(ierr,'imheat_mpi',ilog)
        imheat_mpi = -1
        call memory_monitor(sizeof(imheat_mpi),'imheat_mpi',.true.)


        allocate(offset_imheat(imheat_first:imheat_first+2), stat = ierr)
        call checkerr(ierr,'offset_imheat',ilog)
        offset_imheat = 0
        call memory_monitor(sizeof(offset_imheat),'offset_imheat',.true.)


        allocate(offset_imheat_ijk(imheat_first:imheat_first+2), stat = ierr)
        call checkerr(ierr,'offset_imheat_ijk',ilog)
        offset_imheat_ijk = 0
        call memory_monitor(sizeof(offset_imheat_ijk),'offset_imheat_ijk',.true.)

      end if
        
      if (rank == 0 .and. b_enable_output) then
        if (b_output_trans_binary) then
#ifndef PETSC
          if (imheat_mpi(imheat) < 10) then
            imheat_mpi(imheat) = lun_get()
          end if
#endif
          call binary_file_open(PETSC_COMM_SELF,               &
                       imheat_mpi(imheat), prefix(:l_prfx)//'_o.ebal', &
                       .true.)
        else
          b_rewind_valid = check_rewind_status(prefix(:l_prfx)//'_o.ebal')
          if (b_rewind_valid .and. i_append_sim > 0) then
            open(imheat,file=prefix(:l_prfx)//'_o.ebal',status='unknown',&
                 form='formatted',position='rewind')
          else
            open(imheat,file=prefix(:l_prfx)//'_o.ebal',status='unknown',&
                 form='formatted')
          end if
        end if
          
!c  version information
        if (i_append_sim < 1 .or. .not.b_rewind_valid) then
          if (b_writeversion_tecplot .and. .not. b_output_trans_binary) then
            call writeversion2file(imheat, "#")
          end if
        end if
          
        if (b_output_trans_binary) then
          nvarsimheat = 4  
          tec_variables(1:nvarsimheat) = [character(len=72) ::         &
                        "time", "energy", "water filled volume",       &
                        "gas filled volume"]
          strbuffer = "system energy"
          
          offset_imheat(imheat) = 0  
          call tecplot_binary_write_header(PETSC_COMM_SELF,            &
                       imheat_mpi(imheat), "#!TDV102",'dataset '//     &
                       prefix(:l_prfx),offset_imheat(imheat),.true.,   &
                       .true.)  
          
          call tecplot_binary_write_variable(PETSC_COMM_SELF,          &
                       imheat_mpi(imheat), nvarsimheat,                &
                       tec_variables(1:nvarsimheat),                   &
                       offset_imheat(imheat),.true.,.true.)               
          
          call tecplot_binary_write_zoneinfo(PETSC_COMM_SELF,          &
                       imheat_mpi(imheat),trim(strbuffer),             &
                       offset_imheat(imheat), 1, 1, 1, .true., .true., &
                       b_output_multizone)
          offset_imheat_ijk(imheat) = offset_imheat(imheat) - 5*4
          
          call tecplot_binary_write_section(PETSC_COMM_SELF,           &
                       imheat_mpi(imheat),nvarsimheat,0,               &
                       offset_imheat(imheat),.true.,.true.,            &
                       b_output_multizone)
        else
          if (i_append_sim < 1 .or. .not.b_rewind_valid) then
            write(imheat,'(3a)') 'title = "dataset ',prefix(:l_prfx),'"'
            write(imheat,'(3a)') 'variables = "time", "energy", ',     &
                                 '"water filled volume", ',            &
                                 '"gas filled volume" '
            write(imheat,'(2a)') 'zone t = "system energy", f=point'
          end if
        end if
      end if
        
      if (rank == 0 .and. b_enable_output) then
          
        write(ifls,'(a/72a/)')'system energy',('-',i=1,72)
        write(ifls,'(a/)') prefix(:l_prfx)//'_o.ebal'
        
        write(ifls,'(2a)') 'column   entry                           ',&
                           'unit'
        write(ifls,'(2a)') '1        time                            ',&
                            time_unit
        write(ifls,'(2a)') '2        energy                          ',&
                           'KJ'
        write(ifls,'(2a)') '3        water filled volume             ',&
                           'm^3'
        write(ifls,'(2a/)')'4        gas filled volume               ',&
                           'm^3'
      end if

!c  energy balance contributions

      imheat = imheat + 1
      if (rank == 0 .and. b_enable_output) then
        if (b_output_trans_binary) then  
#ifndef PETSC
          if (imheat_mpi(imheat) < 10) then
            imheat_mpi(imheat) = lun_get()
          end if
#endif
          call binary_file_open(PETSC_COMM_SELF,               &
                       imheat_mpi(imheat), prefix(:l_prfx)//'_o.ebalc',&
                       .true.)
        else
          b_rewind_valid = check_rewind_status(prefix(:l_prfx)//'_o.ebalc')
          if (b_rewind_valid .and. i_append_sim > 0) then
            open(imheat,file=prefix(:l_prfx)//'_o.ebalc',status='unknown',&
                 form='formatted',position='rewind')
          else
            open(imheat,file=prefix(:l_prfx)//'_o.ebalc',status='unknown',&
                 form='formatted')
          end if
        end if
          
!c  version information
        if (i_append_sim < 1 .or. .not.b_rewind_valid) then
          if (b_writeversion_tecplot .and. .not. b_output_trans_binary) then
            call writeversion2file(imheat, "#")
          end if
        end if
          
        if (b_output_trans_binary) then
          nvarsimheat = 4  
          tec_variables(1:nvarsimheat) = [character(len=72) ::"time",  &
                        "inflow","outflow","change in storage"]
          strbuffer = "energy balance"
          
          offset_imheat(imheat) = 0  
          call tecplot_binary_write_header(PETSC_COMM_SELF,            &
                       imheat_mpi(imheat), "#!TDV102",'dataset '//     &
                       prefix(:l_prfx),offset_imheat(imheat),.true.,   &
                       .true.)  
          
          call tecplot_binary_write_variable(PETSC_COMM_SELF,          &
                       imheat_mpi(imheat), nvarsimheat,                &
                       tec_variables(1:nvarsimheat),                   &
                       offset_imheat(imheat),.true.,.true.)               
          
          call tecplot_binary_write_zoneinfo(PETSC_COMM_SELF,          &
                       imheat_mpi(imheat),trim(strbuffer),             &
                       offset_imheat(imheat), 1, 1, 1, .true.,.true.,  &
                       b_output_multizone)
          offset_imheat_ijk(imheat) = offset_imheat(imheat) - 5*4
          
          call tecplot_binary_write_section(PETSC_COMM_SELF,           &
                       imheat_mpi(imheat),nvarsimheat,0,               &
                       offset_imheat(imheat), .true.,.true.,           &
                       b_output_multizone)
        else
          if (i_append_sim < 1 .or. .not.b_rewind_valid) then
            write(imheat,'(3a)') 'title = "dataset ',prefix(:l_prfx),'"'
            write(imheat,'(3a)')                                       &
                         'variables = "time", "inflow", "outflow", ',  &
                         '"change in storage", '
            write(imheat,'(2a)') 'zone t = "energy balance", f=point'
          end if
        end if
      end if
        
      if (rank == 0 .and. b_enable_output) then

        write(ifls,'(a/72a/)')'energy balance contributions',         &
                              ('-',i=1,72)
        write(ifls,'(a/)') prefix(:l_prfx)//'_o.ebalc'
        
        write(ifls,'(2a)') 'column   entry                           ',&
                           'unit'
        write(ifls,'(2a)') '1        time                            ',&
                            time_unit
        write(ifls,'(2a)') '2        total inflow                    ',&
                           'KJ/day'
        write(ifls,'(2a)') '3        total outflow                   ',&
                           'KJ/day'
        write(ifls,'(2a/)')'4        change in storage               ',&
                           'KJ/day'
        
      end if

!c  energy balance error

      imheat = imheat + 1
      if(rank == 0 .and. b_enable_output) then
        if (b_output_trans_binary) then
#ifndef PETSC
          if (imheat_mpi(imheat) < 10) then
            imheat_mpi(imheat) = lun_get()
          end if
#endif
          call binary_file_open(PETSC_COMM_SELF,               &
                       imheat_mpi(imheat), prefix(:l_prfx)//'_o.ebale',&
                       .true.)
        else
          b_rewind_valid = check_rewind_status(prefix(:l_prfx)//'_o.ebale')
          if (b_rewind_valid .and. i_append_sim > 0) then
            open(imheat,file=prefix(:l_prfx)//'_o.ebale',              &
                 status='unknown',form='formatted',position='rewind')
          else
            open(imheat,file=prefix(:l_prfx)//'_o.ebale',              &
                 status='unknown',form='formatted')
          end if
        end if
        
!c  version information
        if (i_append_sim < 1 .or. .not.b_rewind_valid) then
          if (b_writeversion_tecplot .and. .not. b_output_trans_binary) then
            call writeversion2file(imheat, "#")
          end if
        end if
          
        if (b_output_trans_binary) then
          nvarsimheat = 5  
          tec_variables(1:nvarsimheat) = [character(len=72) ::"time",  &
                        "absolute energy balance error",               &
                        "relative energy balance error",               &
                        "absolute cumulative energy balance error",    &
                        "relative cumulative energy balance error"]
          strbuffer = "energy balance error - variably saturated flow"
          
          offset_imheat(imheat) = 0  
          call tecplot_binary_write_header(PETSC_COMM_SELF,            &
                       imheat_mpi(imheat), "#!TDV102",'dataset '//     &
                       prefix(:l_prfx),offset_imheat(imheat),.true.,   &
                       .true.)  
          
          call tecplot_binary_write_variable(PETSC_COMM_SELF,          &
                       imheat_mpi(imheat), nvarsimheat,                &
                       tec_variables(1:nvarsimheat),                   &
                       offset_imheat(imheat),.true.,.true.)               
          
          call tecplot_binary_write_zoneinfo(PETSC_COMM_SELF,          &
                       imheat_mpi(imheat),trim(strbuffer),             &
                       offset_imheat(imheat), 1, 1, 1, .true.,.true.,  &
                       b_output_multizone)
          offset_imheat_ijk(imheat) = offset_imheat(imheat) - 5*4
          
          call tecplot_binary_write_section(PETSC_COMM_SELF,           &
                       imheat_mpi(imheat),nvarsimheat,0,               &
                       offset_imheat(imheat), .true.,.true.,           &
                       b_output_multizone)
        else
          if (i_append_sim < 1 .or. .not.b_rewind_valid) then
            write(imheat,'(3a)') 'title = "dataset ',prefix(:l_prfx),'"'
            write(imheat,'(5a)') 'variables = "time", ',                 &
                         '"absolute energy balance error", ',            &
                         '"relative energy balance error", ',            &
                         '"absolute cumulative energy balance error", ', &
                         '"relative cumulative energy balance error" '
            write(imheat,'(2a)') 'zone t = "energy balance error - ',    &
                                   ' variably saturated flow", f=point'
          end if
        end if
      end if
        
      if (rank == 0 .and. b_enable_output) then

        write(ifls,'(a/72a/)')'mass balance error',                    &
                              ('-',i=1,72)
        write(ifls,'(a/)') prefix(:l_prfx)//'_o.ebale'
        
        write(ifls,'(2a)') 'column   entry                           ',&
                           'unit'
        write(ifls,'(2a)') '1        time                            ',&
                            time_unit
        write(ifls,'(2a)') '2        absolute energy balance error   ',&
                           'm^3'
        write(ifls,'(2a)') '3        relative energy balance error   ',&
                           '% = KJ/KJ in system x 100'
        write(ifls,'(2a)') '4        accumulative absolute energy    ',&
                           'KJ'
        write(ifls,'(a)')  '         balance error'
        write(ifls,'(2a)') '5        accumulative relative energy    ',&
                           '% = KJ/KJ in system x 100'
        write(ifls,'(a)')  '         balance error'
        
      end if

      imheat_last = imheat

      return
      
      end
