!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 875 $
!> $Author: dsu $
!> $Date: 2024-01-21 12:55:48 -0800 (Sun, 21 Jan 2024) $
!> $URL: https://min3psvn.ubc.ca/svn/min3p_thcm/branches/dsu_new_add_2024Jan/src/min3p/opnplfls.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine opnplfls
!c -------------------
!c
!c open postprocessing files for transient data (local chemistry) 
!c
!c written by:      Uli Mayer - May 14, 96
!c
!c last modified:   Uli Mayer - January 30, 98
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c 
!c                                                                    I O
!c passed:   integer*4:
!c           ----------
!c           ilb                = number of current dat set           + -
!c
!c common:   
!c gen.f:    integer*4:
!c           ----------
!c           ilog               = unit number, logbook                + -    
!c           icnv               = unit number, data conversion        + -
!c           l_prfx             = length of prefix of I/O files       + -
!c
!c           character:
!c           ----------
!c           prefix             = prefix name for all I/O files       + -
!c
!c chem.f:   integer*4:
!c           ----------
!c           iaic(nsites)       = pointer array for compressed        + -
!c                                storage of surface site data
!c           iamd(nm+1)         = pointer array to dissolution-       + -
!c                                precipitation reactions
!c           ilbb               = unit number, concentrations of      * +
!c                                             sorbed species
!c                                             - transient data
!c                                               local system
!c           ilbt               = unit number, total aqueous          * +
!c                                             component
!c                                             concentrations
!c                                             - transient data
!c                                               local system
!c           ilbc               = unit number, free species and       * +
!c                                             secondary aqueous
!c                                             species concentrations
!c                                             - transient data
!c                                               local system
!c           ilbac              = unit number, activity coefficients  * +
!c                                             - transient data
!c                                               local system
!c           ilbm               = unit number, master variables       * +
!c                                             - transient data
!c                                               local system
!c           ilbg               = unit number, gas concentrations     * +
!c                                             - transient data
!c                                               local system
!c           ilbgr              = unit number, degassing rates        * +
!c                                             - transient data
!c                                               local system
!c           ilbi               = unit number, rates of intra-aqueous * +
!c                                             kinetic reactions
!c                                             - transient data
!c                                               local system
!c           ilbs               = unit number, saturation indices     * +
!c                                             - transient data
!c                                               local system
!c           ilbv               = unit number, mineral volume         * +
!c                                             fractions
!c                                             - transient data
!c                                               local system
!c           ilbd               = unit number, dissolution-           * +
!c                                             precipitation
!c                                             rates
!c                                             - transient data
!c                                               local system
!c           ilbx               = unit number, saturation indices     * +
!c                                             excluded minerals
!c                                             - transient data
!c                                               local system
!c           nanc               = number of sorbed species            + -
!c                                non-competitive sorption
!c           naq                = number of intra-aqueous kinetic     + -
!c                                reactions
!c           nc                 = number of components including h2o  + -
!c           ng                 = number of gases                     + -
!c           nm                 = number of minerals                  + -
!c           nmx                = number of excluded minerals         + -
!c           nr                 = number of redox couples             + -
!c           nsb                = number of sorbed species            + -
!c           nsb_ion            = number of sorbed species            + -
!c                                (ion-exchange)
!c           nsb_surf           = number of sorbed species            + -
!c                                (surface-complex)
!c           nsites             = number of surface sites             + -
!c           nx                 = number of aqueous complexes         + -
!c
!c           logical:
!c           --------
!c           gas_removal        = .true.  -> degassing of dissolved   + -
!c                                           gases, if confining
!c                                           pressure exceeded
!c           noncompetitive_sorption = logical array for activation   + -   
!c                                     of noncompetitive sorption
!c                                     reactions
!c           ph_output          = .true.  -> output of pH             + -
!c           pe_output          = .true.  -> output of pe and Eh      + -
!c           redox_equil        = .true.  -> equilibrium reactions    + -
!c                                           for redox couples
!c
!c
!c           character:
!c           ----------
!c           isotherm_type(nc)  = definition of sorption isotherm     + -    
!c                                'none' = no sorption
!c                                'linear' = linear adsorption
!c                                'freundlich' = Freundlich isotherm
!c                                'langmuir' = Langmuir isotherm
!c           nameaq(naq)        = names of intra-aqueous kinetic      + -
!c                                reactions
!c           namec(nc)          = component names                     + -
!c           nameg(ng)          = names of gases                      + -
!c           namex(nx)          = names of secondary aqueous species  + -
!c           namem(nm)          = mineral names                       + -
!c           namemx(nmx)        = names of excluded minerals          + -
!c           namemp(ndr*nm)     = names for parallel                  + -
!c                                dissolution-precipitation reactions
!c           namer(nr)          = names of redox couples              + -
!c           namesb(nsb)        = names of sorbed species             + -
!c           namesb_ion(nsb_ion)= names of sorbed species             + -
!c                                (ion-exchange)
!c           namesb_surf(nsb_surf)= names of sorbed species           + -
!c                                  (surface-complex)
!c           output_unit_sb     = output units for surface species    + -
!c           output_unit_sb_ion = output unit for sorption            + -
!c                                reactions of ion-exchange
!c           output_unit_sb_surf= output unit for sorption            + -
!c                                reactions of surface-complex
!c           time_unit_lc       = time unit for output -> 'years'     + -
!c                                                        'days'
!c           
!c local:    integer*4:
!c           ----------
!c           ianc               = counter (non-competitive sorption
!c                                         reactions)
!c           iaq                = counter (intra-aqueous kinetic
!c                                         reactions)
!c           ic                 = counter (components)
!c           ig                 = counter (gases)
!c           im                 = counter (minerals)
!c           imx                = counter (excluded minerals)
!c           ir                 = counter (redox couples)
!c           isb                = counter (sorbed species)
!c           isites             = counter (surface sites)
!c           ix                 = counter (aqueous complexes)
!c           ireac              = counter (reactions)
!c           istart             = pointer
!c           istop              = pointer
!c           l_sufx             = length of file suffix
!c 
!c           character:
!c           ----------
!c           suffix             = file suffix
!c
!c external: -
!c ----------------------------------------------------------------------

      subroutine opnplfls(ilb)

#ifdef PETSC
#include <petscversion.h>
#if (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR >= 8)
#include <petsc/finclude/petscsys.h>
      use petscsys
#endif
#endif


      use parm
      use gen
      use chem
      use nobleGasIngrowth, only : b_use_ngi, ngre_i, name_ngre_i
      use file_unit, only : lun_get
#ifdef PETSC
      use petsc_mpi_common, only : petsc_mpi_finalize
#endif
      use module_binary_mpiio, only : binary_file_open
      
      implicit none
#ifdef PETSC
#if (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR >= 6 && PETSC_VERSION_MINOR < 8)
#include <petsc/finclude/petscsys.h>
#elif (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR < 6)
#include <finclude/petscsys.h>
#endif
#endif
      
      integer :: ilb
      
      integer :: i, iaq, ianc, ic, ig, im, imx, ir, ireac, isb,        &
                 isites, istart, istop, ix, ingre, l_sufx

      character*2 suffix

!c     write(*,'(/a)') 'enter routine opnplfls ...'

!c  assign file suffix

      !rewind(icnv)              !Deprecated, use internal convert instead. DSU
      if (ilb.lt.10) then
        !write(icnv,'(i1)') ilb
        !rewind(icnv)
        !read(icnv,'(a2)') suffix
        write(suffix,'(i1)') ilb
        l_sufx = 1
      elseif (ilb.ge.10.and.ilb.lt.100) then
        !write(icnv,'(i2)') ilb
        !rewind(icnv)
        !read(icnv,'(a2)') suffix
        write(suffix,'(i2)') ilb
        l_sufx = 2
      elseif (ilb.ge.100) then
        if (rank == 0) then
          write(ilog,'(/a)')'error in input file'
          write(ilog,'(a)')'max. number of data sets exceeded'
          write(ilog,'(a)')'abnormal exit in routine opnplfls'
          close(ilog)
        end if
#ifdef DEBUG
        write(idbg,'(/a)') 'error in input file'
        write(idbg,'(a)') 'max. number of data sets exceeded'
        write(idbg,'(a)') 'abnormal exit in routine opnplfls'
        close(idbg)
#endif
#ifdef PETSC
        call petsc_mpi_finalize
#endif
        stop
      end if

!c  assign unit numbers

      !ilbt = 40        !total aqueous component concentrations
      !ilbc = 41        !species concentrations
      !ilbm = 42        !master variables
      !ilbg = 43        !partial gas pressures
      !ilbgr = 50       !degassing rates
      !ilbi = 44        !intra-aqueous kinetic reactions
      !ilbb = 45        !sorbed species concentrations
      !ilbs = 46        !mineral saturation indices
      !ilbv = 47        !mineral volume fractions
      !ilbd = 48        !mineral dissolution-precipitation rates
      !ilbx = 49        !saturation indices (excluded minerals)
      
      ilbt = lun_get()        !total aqueous component concentrations
      ilbc = lun_get()        !species concentrations
      ilbm = lun_get()        !master variables
      ilbg = lun_get()        !partial gas pressures
      ilbgr = lun_get()       !degassing rates
      ilbi = lun_get()        !intra-aqueous kinetic reactions
      ilbb = lun_get()        !sorbed species concentrations
      ilbs = lun_get()        !mineral saturation indices
      ilbv = lun_get()        !mineral volume fractions
      ilbd = lun_get()        !mineral dissolution-precipitation rates
      ilbx = lun_get()        !saturation indices (excluded minerals)
      ilbac = lun_get()       !species concentrations

!cdsu concentration of radioelement related to noble gas ingrowth
      if (b_use_ngi .and. ngre_i > 0) then
        ilbre = lun_get()       !species concentrations
      end if

!c  open files
!c
!c  total aqueous component concentrations
!c ----------------------------------------------------------------------

      if (b_output_trans_binary) then
        call binary_file_open(PETSC_COMM_SELF,                         &
                     ilbt, prefix(:l_prfx)//'_'//                      &
                     suffix(:l_sufx)//'.lbt', .true.)
      else
        open(ilbt,file=prefix(:l_prfx)//'_'//                          &
                       suffix(:l_sufx)//'.lbt',                        &
                  status='unknown',form='formatted')
      end if

!c  write file information
      if (rank == 0) then
          
        write(ifls,'(/a/72a)')                                        &
              'Total aqueous component concentrations',               &
              ('-',i=1,72)
                                                                       
        write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                    &
                            suffix(:l_sufx)//'.lbt'
                                                                       
        write(ifls,'(2a)')  'column   entry                           ',&
                            'unit'                                       
        if (ph_sweep) then                                               
          write(ifls,'(a)')                                           &
          '1        pH                              -'                   
        else                                                             
          write(ifls,'(2a)')                                          &
          '1        time                            ',time_unit_lc
        end if
        do ic = 1,nc-1
          if (ic.lt.9) then
            write(ifls,'(i1,8x,a30,2x,a)') ic+1,namec(ic),'moles/l h2o'
          else
            write(ifls,'(i2,7x,a30,2x,a)') ic+1,namec(ic),'moles/l h2o'
          end if
        end do
      
      end if

!c  species concentrations
!c ----------------------------------------------------------------------
      if (b_output_trans_binary) then
        call binary_file_open(PETSC_COMM_SELF,                 &
                     ilbc, prefix(:l_prfx)//'_'//                      &
                     suffix(:l_sufx)//'.lbc', .true.)
      else
        open(ilbc,file=prefix(:l_prfx)//'_'//                          &
                       suffix(:l_sufx)//'.lbc',                        &
                  status='unknown',form='formatted')
      end if

!c  write file information
      if (rank == 0) then
          
      write(ifls,'(/a/72a)')                                          &
     &      'Species concentrations',                                 &
     &      ('-',i=1,72)
                                                                       
      write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                      &
     &                    suffix(:l_sufx)//'.lbc'
                                                                       
      write(ifls,'(2a)')  'column   entry                           ',&
     &                    'unit'                                       
      if (ph_sweep) then                                               
        write(ifls,'(a)')                                             &
     &  '1        pH                              -'                   
      else                                                             
        write(ifls,'(2a)')                                            &
     &  '1        time                            ',time_unit_lc
      end if
      do ic = 1,nc-1
        if (ic.lt.9) then
          write(ifls,'(i1,8x,a30,2x,a)') ic+1,namec(ic),'moles/l h2o'
        else
          write(ifls,'(i2,7x,a30,2x,a)') ic+1,namec(ic),'moles/l h2o'
        end if
      end do
      do ix = 1,nx
        if (ix+nc-1.lt.9) then
          write(ifls,'(i1,8x,a30,2x,a)') ix+nc,namex(ix),'moles/l h2o'
        else
          write(ifls,'(i2,7x,a30,2x,a)') ix+nc,namex(ix),'moles/l h2o'
        end if
      end do
      
      end if
      
!c  activity coefficients
!c ----------------------------------------------------------------------
      if (b_output_activity) then 
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,                       &
                       ilbac, prefix(:l_prfx)//'_'//                   &
                       suffix(:l_sufx)//'.lbac', .true.)
        else
          open(ilbac,file=prefix(:l_prfx)//'_'//                       &
                         suffix(:l_sufx)//'.lbac',                     &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then
            
          write(ifls,'(/a/72a)')                                       &
     &          'Species activity coefficients',                       &
     &          ('-',i=1,72)
                                                                        
          write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                   &
     &                        suffix(:l_sufx)//'.lbac'
                                                                           
          write(ifls,'(2a)')  'column   entry                           ',&
     &                        'unit'                                       
          if (ph_sweep) then                                               
            write(ifls,'(a)')                                          &
     &      '1        pH                              -'                   
          else                                                             
            write(ifls,'(2a)')                                         &
     &      '1        time                            ',time_unit_lc
          end if
          do ic = 1,nc-1
            if (ic.lt.9) then
              write(ifls,'(i1,8x,a30,2x,a)') ic+1,namec(ic),'-'
            else
              write(ifls,'(i2,7x,a30,2x,a)') ic+1,namec(ic),'-'
            end if
          end do
          do ix = 1,nx
            if (ix+nc-1.lt.9) then
              write(ifls,'(i1,8x,a30,2x,a)') ix+nc,namex(ix),'-'
            else
              write(ifls,'(i2,7x,a30,2x,a)') ix+nc,namex(ix),'-'
            end if
          end do
        
        end if
      end if

!c  master variables
!c ----------------------------------------------------------------------
      if (b_output_trans_binary) then
        call binary_file_open(PETSC_COMM_SELF,                 &
                     ilbm, prefix(:l_prfx)//'_'//                      &
                     suffix(:l_sufx)//'.lbm', .true.)
      else
        open(ilbm,file=prefix(:l_prfx)//'_'//                          &
                       suffix(:l_sufx)//'.lbm',                        &
                  status='unknown',form='formatted')
      end if

!c  write file information
      if (rank == 0) then
          
      write(ifls,'(/a/72a)')                                          &
     &      'Master variables',                                       &
     &      ('-',i=1,72)
                                                                       
      write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                      &
     &                    suffix(:l_sufx)//'.lbm'
                                                                       
      write(ifls,'(2a)')  'column   entry                           ',&
     &                    'unit'                                       
      if (ph_sweep) then                                               
        write(ifls,'(a)')                                             &
     &  '1        pH                              -'                   
      else                                                             
        write(ifls,'(2a)')                                            &
     &  '1        time                            ',time_unit_lc       
      end if                                                           
      if ((ph_output).and.(pe_output)) then                            
        write(ifls,'(a,30x,a)')  '2        pH','-'                     
        write(ifls,'(a,30x,a)')  '3        pe','-'                     
        write(ifls,'(a,30x,a)')  '4        Eh','-'                     
        write(ifls,'(a,18x,a)')  '5        ionic strength','-'         
        write(ifls,'(a,12x,a)')  '6        carbonate alkalinity',     &
     &                           'eq/L'                                
        write(ifls,'(a,8x,a)')   '7        non-carbonate alkalinity', &
     &                           'eq/L'                                
        write(ifls,'(a,22x,a)')  '8        alkalinity','eq/L'          
        write(ifls,'(a,12x,a)')  '9        carbonate alkalinity',     &
     &                           'mg/L CaCO3'                          
        write(ifls,'(a,8x,a)')   '10       non-carbonate alkalinity', &
     &                           'mg/L CaCO3'                          
        write(ifls,'(a,22x,a)')  '11       alkalinity','mg/L CaCO3'    
        write(ifls,'(a,21x,a)')  '12       temperature','C'            
      elseif ((.not.ph_output).and.(pe_output)) then                   
        write(ifls,'(a,30x,a)')  '2        pe','-'                     
        write(ifls,'(a,30x,a)')  '3        Eh','-'                     
        write(ifls,'(a,18x,a)')  '4        ionic strength','-'         
        write(ifls,'(a,12x,a)')  '5        carbonate alkalinity',     &
     &                           'eq/L'                                
        write(ifls,'(a,8x,a)')   '6        non-carbonate alkalinity', &
     &                           'eq/L'                                
        write(ifls,'(a,22x,a)')  '7        alkalinity','eq/L'          
        write(ifls,'(a,12x,a)')  '8        carbonate alkalinity',     &
     &                           'mg/L CaCO3'                          
        write(ifls,'(a,8x,a)')   '90       non-carbonate alkalinity', &
     &                           'mg/L CaCO3'                          
        write(ifls,'(a,22x,a)')  '10       alkalinity','mg/L CaCO3'    
        write(ifls,'(a,21x,a)')  '11       temperature','C'            
      elseif ((ph_output).and.(.not.pe_output)) then                   
        write(ifls,'(a,30x,a)')  '2        pH','-'                     
        write(ifls,'(a,18x,a)')  '3        ionic strength','-'         
        write(ifls,'(a,12x,a)')  '4        carbonate alkalinity',     &
     &                           'eq/L'                                
        write(ifls,'(a,8x,a)')   '5        non-carbonate alkalinity', &
     &                           'eq/L'                                
        write(ifls,'(a,22x,a)')  '6        alkalinity','eq/L'          
        write(ifls,'(a,12x,a)')  '7        carbonate alkalinity',     &
     &                           'mg/L CaCO3'                          
        write(ifls,'(a,8x,a)')   '8        non-carbonate alkalinity', &
     &                           'mg/L CaCO3'
        write(ifls,'(a,22x,a)')  '9        alkalinity','mg/L CaCO3'
        write(ifls,'(a,21x,a)')  '10       temperature','C'
      end if
      
      end if

!c  partial gas pressures
!c ----------------------------------------------------------------------

      if (ng.gt.0) then
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,               &
                       ilbg, prefix(:l_prfx)//'_'//                    &
                       suffix(:l_sufx)//'.lbg', .true.)
        else
          open(ilbg,file=prefix(:l_prfx)//'_'//                        &
                         suffix(:l_sufx)//'.lbg',                      &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then
            
        write(ifls,'(/a/72a)')                                        &
     &        'Partial gas pressures',                                &
     &        ('-',i=1,72)
                                                                       
        write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                    &
     &                      suffix(:l_sufx)//'.lbg'
                                                                       
        write(ifls,'(2a)')'column   entry                           ',&
     &                    'unit'                                       
        if (ph_sweep) then                                             
          write(ifls,'(a)')                                           &
     &    '1        pH                              -'                 
        else                                                           
          write(ifls,'(2a)')                                          &
     &    '1        time                            ',time_unit_lc     
        end if                                                         
        do ig = 1,ng                                                   
          if (ig.lt.9) then                                            
            write(ifls,'(i1,8x,a30,2x,a)') ig+1,nameg(ig),'atm'         
          else                                                         
            write(ifls,'(i2,7x,a30,2x,a)') ig+1,nameg(ig),'atm'         
          end if                                                       
        end do                                                         
        write(ifls,'(2a)')'1+ng+1   total gas pressure              ',&
     &                       'atm'
        
        end if
    
!c  degassing rates

        if (gas_removal) then

          if (b_output_trans_binary) then
            call binary_file_open(PETSC_COMM_SELF,             &
                         ilbgr, prefix(:l_prfx)//'_'//                 &
                         suffix(:l_sufx)//'.lbgr', .true.)
          else 
            open(ilbgr,file=prefix(:l_prfx)//'_'//                     &
                          suffix(:l_sufx)//'.lbgr',                    &
                     status='unknown',form='formatted')
          end if

!c  write file information
          if (rank == 0) then
              
            write(ifls,'(/a/72a)')                                     &
     &            'Degassing rates',                                   &
     &            ('-',i=1,72)
                                                                        
            write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                 &
     &                          suffix(:l_sufx)//'.lbgr'
                                                                        
            write(ifls,'(2a)')                                         &
     &      'column   entry                           ','unit'          
            if (ph_sweep) then                                          
              write(ifls,'(a)')                                        &
     &        '1        pH                               -'             
            else                                                        
              write(ifls,'(2a)')                                       &
     &        '1        time                            ',time_unit_lc   
            end if                                                       
            do ig = 1,ng                                                 
              if (ig.lt.9) then                                          
                write(ifls,'(i1,8x,a30,2x,a)') ig+1,nameg(ig),         &
     &                                        'mol L^-1 d^-1'            
              else                                                       
                write(ifls,'(i2,7x,a30,2x,a)') ig+1,nameg(ig),         &
     &                                        'mol L^-1 d^-1'
              end if
            end do
          
          end if

        end if       !(gas_removal)

      end if         !(ng.gt.0)
 
!c  oxidation-reduction rates
!c ----------------------------------------------------------------------

      if (naq.eq.0.and.(nr.gt.0).and.(.not.redox_equil)) then

        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,               &
                       ilbi, prefix(:l_prfx)//'_'//                    &
                       suffix(:l_sufx)//'.lbi', .true.)
        else 
          open(ilbi,file=prefix(:l_prfx)//'_'//                        &
                         suffix(:l_sufx)//'.lbr',                      &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then
            
          write(ifls,'(/a/72a)')                                        &
     &          'Oxidation-reduction rates',                            &
     &          ('-',i=1,72)
                                                                         
          write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                    &
     &                        suffix(:l_sufx)//'.lbr'
                                                                         
          write(ifls,'(2a)')'column   entry                            ',&
     &                       'unit'                                       
          if (ph_sweep) then                                              
            write(ifls,'(a)')                                           &
     &      '1        pH                               -'                
          else                                                           
            write(ifls,'(2a)')                                          &
     &      '1        time                             ',time_unit_lc     
          end if                                                          
          do ir = 1,nr                                                    
            if (ir.lt.9) then                                             
              write(ifls,'(i1,8x,a30,2x,a)') ir+1,namer(ir),            &
     &                                     'moles/l h2o/day'              
            else                                                          
              write(ifls,'(i2,7x,a30,2x,a)') ir+1,namer(ir),            &
     &                                     'moles/l h2o/day'
            end if
          end do
        
        end if

      end if         !((nr.gt.0......)

!c  intra-aqueous kinetic reactions
!c ----------------------------------------------------------------------

      if (naq.gt.0) then
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,               &
                       ilbi, prefix(:l_prfx)//'_'//                    &
                       suffix(:l_sufx)//'.lbi', .true.)
        else 
          open(ilbi,file=prefix(:l_prfx)//'_'//                        &
                         suffix(:l_sufx)//'.lbi',                      &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then
            
          write(ifls,'(/a/72a)')                                       &
     &          'Rates of intra-aqueous kinetic reactions',            &
     &          ('-',i=1,72)
                                                                        
          write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                   &
     &                        suffix(:l_sufx)//'.lbi'
                                                                          
          write(ifls,'(2a)') 'column   entry                           ',&
     &                       'unit'                                       
          if (ph_sweep) then                                              
            write(ifls,'(a)')                                          &
     &      '1        pH                              -'                  
          else                                                            
            write(ifls,'(2a)')                                         &
     &      '1        time                            ',time_unit_lc      
          end if                                                          
          do iaq = 1,naq                                                  
            if (iaq.lt.9) then                                            
              write(ifls,'(i1,8x,a30,2x,a)') iaq+1,nameaq(iaq),        &
     &                                     'moles/l h2o/day'              
            else                                                          
              write(ifls,'(i2,7x,a30,2x,a)') iaq+1,nameaq(iaq),        &
     &                                     'moles/l h2o/day'
            end if
          end do
        
        end if

      end if         !(naq.gt.0......)

!c  concentrations of sorbed species
!c ----------------------------------------------------------------------

      if (nsb_ion.gt.0.or.nsb_surf.gt.0.or.noncompetitive_sorption) then
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,                       &
                       ilbb, prefix(:l_prfx)//'_'//                    &
                       suffix(:l_sufx)//'.lbb', .true.)
        else 
          open(ilbb,file=prefix(:l_prfx)//'_'//                        &
                         suffix(:l_sufx)//'.lbb',                      &
                    status='unknown',form='formatted')
        end if
        
        if (rank == 0) then

!c  write file information
            
          write(ifls,'(/a/72a)')                                       &
     &          'Sorbed species concentrations ',                      &
     &          ('-',i=1,72)
                                                                        
          write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                   &
     &                        suffix(:l_sufx)//'.lbb'
                                                                          
          write(ifls,'(2a)') 'column   entry                           ',&
     &                       'unit'                                       
          if (ph_sweep) then                                              
            write(ifls,'(a)')                                          &
     &      '1        pH                              -'                
          else                                                          
            write(ifls,'(2a)')                                         &
     &      '1        time                            ',time_unit_lc
          end if

!c  non-competitive sorption reactions

        if (noncompetitive_sorption) then

          ianc = 0
          do ic = 1,nc-1
              if (isotherm_type(ic).ne.'none') then
                ianc = ianc+1
                if (ianc.lt.9) then
                  write(ifls,'(i1,8x,a30,2x,a)') ianc+1,namec(ic),   &
                                                  'moles/l bulk'           
                else                                                     
                  write(ifls,'(i2,7x,a30,2x,a)') ianc+1,namec(ic),   &
                                                 'moles/l bulk'
                end if
              end if
          end do
 
        end if

!c  competitive sorption reactions

!c  primary surface species

        if (nsb_ion.gt.0.or.nsb_surf.gt.0) then

          do isites = 1,nsites
            ic = iaic(isites)
            if (isites.lt.9) then
              write(ifls,'(i1,8x,a30,2x,a)') isites+nanc+1,namec(ic), &
                                            output_unit_sb_surf             
            else                                                       
              write(ifls,'(i2,7x,a30,2x,a)') isites+nanc+1,namec(ic), &
                                            output_unit_sb_surf
            end if
          end do

!c  secondary surface species

          do isb = 1,nsb_ion
            if (isb+nsites.lt.9) then
              write(ifls,'(i1,8x,a30,2x,a)') isb+nsites+nanc+1,       &
                                            namesb_ion(isb),          &
                                            output_unit_sb_ion             
            else                                                       
              write(ifls,'(i2,7x,a30,2x,a)') isb+nsites+nanc+1,       &
                                            namesb_ion(isb),          &
                                            output_unit_sb_ion
            end if
          end do
          
          do isb = 1,nsb_surf
            if (isb+nsites.lt.9) then
              write(ifls,'(i1,8x,a30,2x,a)') isb+nsites+nanc+1,       &
                                            namesb_surf(isb),         &
                                            output_unit_sb_surf             
            else                                                       
              write(ifls,'(i2,7x,a30,2x,a)') isb+nsites+nanc+1,       &
                                            namesb_surf(isb),         &
                                            output_unit_sb_surf
            end if
          end do

        end if
        
        end if

      end if      !(nsb.gt.0.or.noncompetitive_sorption)

!c  mineral saturation indices
!c ----------------------------------------------------------------------

      if (nm.gt.0) then
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,               &
                       ilbs, prefix(:l_prfx)//'_'//                    &
                       suffix(:l_sufx)//'.lbs', .true.)
        else 
          open(ilbs,file=prefix(:l_prfx)//'_'//                        &
                         suffix(:l_sufx)//'.lbs',                      &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then
          write(ifls,'(/a/72a)')                                       &
     &          'Mineral saturation indices',                          &
     &          ('-',i=1,72)
                                                                        
          write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                   &
     &                        suffix(:l_sufx)//'.lbs'
                                                                          
          write(ifls,'(2a)') 'column   entry                           ',&
     &                       'unit'                                       
          if (ph_sweep) then                                              
            write(ifls,'(a)')                                          &
     &      '1        pH                              -'                  
          else                                                            
            write(ifls,'(2a)')                                         &
     &      '1        time                            ',time_unit_lc
          end if
          do im = 1,nm
            if (im.lt.9) then
              write(ifls,'(i1,8x,a30,2x,a)') im+1,namem(im),'-'  
            else
              write(ifls,'(i2,7x,a30,2x,a)') im+1,namem(im),'-'  
            end if
          end do        
        end if

!c  mineral volume fractions
!c ----------------------------------------------------------------------
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,               &
                       ilbv, prefix(:l_prfx)//'_'//                    &
                       suffix(:l_sufx)//'.lbv', .true.)
        else 
          open(ilbv,file=prefix(:l_prfx)//'_'//                        &
                         suffix(:l_sufx)//'.lbv',                      &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then
            
        write(ifls,'(/a/72a)')                                         &
     &        'Mineral volume fractions',                              &
     &        ('-',i=1,72)
                                                                        
        write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                     &
     &                            suffix(:l_sufx)//'.lbv'
                                                                        
        write(ifls,'(2a)') 'column   entry                           ',&
     &                     'unit'                                       
        if (ph_sweep) then                                              
          write(ifls,'(a)')                                            &
     &    '1        pH                              -'                  
        else                                                            
          write(ifls,'(2a)')                                           &
     &    '1        time                            ',time_unit_lc
        end if 
        do im = 1,nm
          if (im.lt.9) then
            write(ifls,'(i1,8x,a30,2x,a)') im+1,namem(im),'-'
          else
            write(ifls,'(i2,7x,a30,2x,a)') im+1,namem(im),'-'
          end if
        end do  
        
        end if

!c  mineral dissolution-precipitation rates
!c ----------------------------------------------------------------------
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,               &
                       ilbd, prefix(:l_prfx)//'_'//                    &
                       suffix(:l_sufx)//'.lbd', .true.)
        else 
          open(ilbd,file=prefix(:l_prfx)//'_'//                        &
                         suffix(:l_sufx)//'.lbd',                      &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then

        write(ifls,'(/a/72a)')                                        &
     &        'Dissolution-precipitation rates',                      &
     &        ('-',i=1,72)
                                                                       
        write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                    &
     &                            suffix(:l_sufx)//'.lbd'
                                                                       
        write(ifls,'(2a)')'column   entry                           ',&
     &                    'unit'                                       
        if (ph_sweep) then                                             
          write(ifls,'(a)')                                           &
     &    '1        pH                              -'                 
        else                                                           
          write(ifls,'(2a)')                                          &
     &    '1        time                            ',time_unit_lc     
        end if                                                         
        istart = iamd(1)                                               
        istop = iamd(nm+1)-1                                           
        do ireac = istart,istop                                        
          if (ireac.lt.9) then                                         
            write(ifls,'(i1,8x,a30,2x,a)') ireac+1,namemp(ireac),     &
     &                                    'moles/l bulk/day'           
          else                                                         
            write(ifls,'(i2,7x,a30,2x,a)') ireac+1,namemp(ireac),     &
     &                                    'moles/l bulk/day'
          end if
        end do
        
        end if

      end if              !(nm.gt.0)

!c  saturation indices (excluded minerals)
!c ----------------------------------------------------------------------

      if (nmx.gt.0) then
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,               &
                       ilbx, prefix(:l_prfx)//'_'//                    &
                       suffix(:l_sufx)//'.lbx', .true.)
        else 
          open(ilbx,file=prefix(:l_prfx)//'_'//                        &
                         suffix(:l_sufx)//'.lbx',                      &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then

        write(ifls,'(/a/72a)')                                        &
     &        'Saturation indices (excluded minerals)',               &
     &        ('-',i=1,72)
                                                                       
        write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                    &
     &                      suffix(:l_sufx)//'.lbx'
                                                                       
        write(ifls,'(2a)')'column   entry                           ',&
     &                    'unit'                                       
        if (ph_sweep) then                                             
          write(ifls,'(a)')                                           &
     &    '1        pH                              -'                 
        else                                                           
          write(ifls,'(2a)')                                          &
     &    '1        time                            ',time_unit_lc
        end if
        do imx = 1,nmx
          if (imx.lt.9) then
            write(ifls,'(i1,8x,a30,2x,a)') imx+1,namemx(imx),'-'
          else
            write(ifls,'(i2,7x,a30,2x,a)') imx+1,namemx(imx),'-'
          end if
        end do
        
        end if

      end if                !(nmx.gt.0)

!cdsu ----------------------------------------------------------------------
!cdsu concentration of radioelement related to noble gas ingrowth
!cdsu ----------------------------------------------------------------------
      if (b_use_ngi .and. ngre_i > 0) then
        if (b_output_trans_binary) then
          call binary_file_open(PETSC_COMM_SELF,                       &
                       ilbre, prefix(:l_prfx)//'_'//                   &
                       suffix(:l_sufx)//'.lbre', .true.)
        else
          open(ilbre,file=prefix(:l_prfx)//'_'//                       &
                         suffix(:l_sufx)//'.lbre',                     &
                    status='unknown',form='formatted')
        end if

!c  write file information
        if (rank == 0) then
          
          write(ifls,'(/a/72a)')                                        &
                'Total concentration of radioelements',               &
                ('-',i=1,72)
                                                                       
          write(ifls,'(/a/)') prefix(:l_prfx)//'_'//                    &
                              suffix(:l_sufx)//'.lbre'
                                                                       
          write(ifls,'(2a)')  'column   entry                           ',&
                              'unit'                                       
          if (ph_sweep) then                                               
            write(ifls,'(a)')                                          &
            '1        pH                              -'                   
          else                                                             
            write(ifls,'(2a)')                                         &
            '1        time                            ',time_unit_lc
          end if
          do ingre = 1,ngre_i
            if (ingre.lt.9) then
              write(ifls,'(i1,8x,a30,2x,a)') ingre+1,                  &
                    name_ngre_i(ingre),'mg kg^-1 solid or ppm'
            else
              write(ifls,'(i2,7x,a30,2x,a)') ingre+1,                  &
                    name_ngre_i(ingre),'mg kg^-1 solid or ppm'
            end if
          end do
      
        end if

      end if

      return
      end
