!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 850 $
!> $Author: dsu $
!> $Date: 2023-01-27 08:58:23 -0800 (Fri, 27 Jan 2023) $
!> $URL: https://github.com/min3p-ubc/min3p/src/min3p/tprfrtlc_faceflux.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine tprfvs
!c -----------------
!c
!c write transient data of interface flux for aqueous species 
!c to output file
!c
!c written by:      Danyang Su - Nov 27, 2017
!c
!c last modified:   -
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c   
!c                                                                    I O
!c
!c passed:   integer*4:
!c           ----------
!c           ivol               = pointer to current control volume   + -
!c           jvol               = pointer to current control volume   + -
!c
!c common:
!c gen.f:    real*8:
!c           -------
!c
!c           logical:
!c           --------
!c
!c
!c local:    real*8:
!c           ------- 
!c
!c 
!c --------------------------------------------------------------------------

      subroutine tprfrtlc_faceflux(ivol,jvol,igb,ngb_tstep,flag_skip)
 
#ifdef PETSC
#include <petscversion.h>
#if (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR >= 8)
#include <petsc/finclude/petscsys.h>
      use petscsys
#endif
#endif
      use gen, only : ngb_vol_ijface_jtemp, xg, yg, zg,nfloatbit,          &
                      delt, realbuffer_gb, ifrt, offset_ifrt,              &
                      ngb_vol_ijface_area, offset_ifrt_ijk,                &
                      ngb_vol_ijface_velratio, time_io, n, delt,           &
                      mtime, mtime_append, i_append_sim, time_io_rs,       &
                      ifrt_vx_adv_accu,ifrt_vy_adv_accu,ifrt_vz_adv_accu,  &
                      ifrt_vx_dif_accu,ifrt_vy_dif_accu,ifrt_vz_dif_accu,  &
                      ifrt_vx_mig_accu,ifrt_vy_mig_accu,ifrt_vz_mig_accu,  &
                      ifrt_vx_tot_accu,ifrt_vy_tot_accu,ifrt_vz_tot_accu,  &
                      ascii_fmt, cnew, cx, totcnew, cinfrt_va, cinfrt_da,  &
                      cinfvs_a, pornew, sanew, type_averaging_De,          &
                      b_output_trans_binary, ilog
      
      use multidiff, only : multi_diff, delta_totviscnew,              &
                            delta_electromignew, cinfrt_mcd
                            
      use module_binary_mpiio, only : binary_write_data
      
      use file_utility, only : reposition_file 

#ifdef OPENMP
      use omp_lib 
#endif 

      implicit none
#ifdef PETSC
#if (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR >= 6 && PETSC_VERSION_MINOR < 8)
#include <petsc/finclude/petscsys.h>
#elif (PETSC_VERSION_MAJOR >= 3 && PETSC_VERSION_MINOR < 6)
#include <finclude/petscsys.h>
#endif
#endif
      
      integer :: ivol, jvol, jtemp, igb, ngb_tstep
      logical :: flag_skip

      !c local variables
      integer :: i1, nvars, ic, tid, irecord
      real*8 :: areai, velxratio, velyratio, velzratio,                &
                aflux_adv, aflux_dif, aflux_mig, aflux_tot,            &
                vela_adv, vela_dif, vela_mig, vela_tot,                &
                vela_adv_x, vela_dif_x, vela_mig_x, vela_tot_x,        &
                vela_adv_y, vela_dif_y, vela_mig_y, vela_tot_y,        &
                vela_adv_z, vela_dif_z, vela_mig_z, vela_tot_z
      
      character*1 :: iups   
      real*8 :: rdummys(25)      
      real*8, external :: fluxv_vl, fluxd, fluxv_vl_dp, fluxd_dp
      external elecmigration

      real*8, parameter :: r0 = 0.0d0, r1 = 1.0d0      
      
      i1 = ngb_vol_ijface_jtemp(igb)

      if (i1 <= 0) then
        return
      end if

#ifdef OPENMP
      tid = omp_get_thread_num() + 1
#else
      tid = 1
#endif
      
      areai = ngb_vol_ijface_area(igb)
      velxratio = ngb_vol_ijface_velratio(1,igb)
      velyratio = ngb_vol_ijface_velratio(2,igb)
      velzratio = ngb_vol_ijface_velratio(3,igb)

!c compute flux along the control volume interface

      if (multi_diff) then
        call totdyvisc(ivol,jvol,cnew(:,ivol),cx(:,ivol),          &
                       cnew(:,jvol),cx(:,jvol),                    &
                       delta_totviscnew(:,tid))

        call elecmigration(ivol,jvol,cnew(:,ivol),cx(:,ivol),      &
                           cnew(:,jvol),cx(:,jvol),                &
                           delta_electromignew(:,tid))
      end if
      
      do ic = 1, n

        aflux_adv = r0
        aflux_dif = r0
        aflux_mig = r0
        aflux_tot = r0
!c  compute aqueous phase flux

        if (multi_diff) then 

          aflux_adv = fluxv_vl(totcnew(ic,ivol),                       &    !advective term
                               totcnew(ic,jvol),                       &
                               ivol,jvol,cinfrt_va(i1),ic)
          aflux_dif = - fluxd(r0,delta_totviscnew(ic,tid),             & !diffusive term
                              cinfrt_mcd(i1))
          aflux_mig = - fluxd(r0,delta_electromignew(ic,tid),          & !electromigration term
                              cinfrt_mcd(i1))              
        else

!c ---------------- fick's law, business as usual -------------------------     
          aflux_adv = fluxv_vl(totcnew(ic,ivol),                       &    !advective term
                               totcnew(ic,jvol),                       &
                               ivol,jvol,                              &
                               cinfrt_va(i1),ic)                     
          aflux_dif = - fluxd(totcnew(ic,ivol),                        &    !dispersive term
                              totcnew(ic,jvol),                        &
                              cinfrt_da(i1))
        end if

!c  total flux

        aflux_tot = aflux_adv + aflux_dif + aflux_mig
        
!c  velocity is the flux (m^3/day) divided
!c  by the interfacial area between the two control volumes

        vela_adv = aflux_adv / areai * 1.0d+3
        vela_dif = aflux_dif / areai * 1.0d+3
        vela_mig = aflux_mig / areai * 1.0d+3
        vela_tot = aflux_tot / areai * 1.0d+3
        
        vela_adv_x = vela_adv * velxratio
        vela_adv_y = vela_adv * velyratio
        vela_adv_z = vela_adv * velzratio
       
        vela_dif_x = vela_dif * velxratio
        vela_dif_y = vela_dif * velyratio
        vela_dif_z = vela_dif * velzratio
        
        vela_mig_x = vela_mig * velxratio
        vela_mig_y = vela_mig * velyratio
        vela_mig_z = vela_mig * velzratio
        
        vela_tot_x = vela_tot * velxratio
        vela_tot_y = vela_tot * velyratio
        vela_tot_z = vela_tot * velzratio

        ifrt_vx_adv_accu(ic,igb) = ifrt_vx_adv_accu(ic,igb) + vela_adv_x*delt
        ifrt_vy_adv_accu(ic,igb) = ifrt_vy_adv_accu(ic,igb) + vela_adv_y*delt
        ifrt_vz_adv_accu(ic,igb) = ifrt_vz_adv_accu(ic,igb) + vela_adv_z*delt

        ifrt_vx_dif_accu(ic,igb) = ifrt_vx_dif_accu(ic,igb) + vela_dif_x*delt
        ifrt_vy_dif_accu(ic,igb) = ifrt_vy_dif_accu(ic,igb) + vela_dif_y*delt
        ifrt_vz_dif_accu(ic,igb) = ifrt_vz_dif_accu(ic,igb) + vela_dif_z*delt

        ifrt_vx_mig_accu(ic,igb) = ifrt_vx_mig_accu(ic,igb) + vela_mig_x*delt
        ifrt_vy_mig_accu(ic,igb) = ifrt_vy_mig_accu(ic,igb) + vela_mig_y*delt
        ifrt_vz_mig_accu(ic,igb) = ifrt_vz_mig_accu(ic,igb) + vela_mig_z*delt

        ifrt_vx_tot_accu(ic,igb) = ifrt_vx_tot_accu(ic,igb) + vela_tot_x*delt
        ifrt_vy_tot_accu(ic,igb) = ifrt_vy_tot_accu(ic,igb) + vela_tot_y*delt
        ifrt_vz_tot_accu(ic,igb) = ifrt_vz_tot_accu(ic,igb) + vela_tot_z*delt

!c  write data back to file
        if (.not.flag_skip) then
          nvars = 25 
          if (b_output_trans_binary) then
            realbuffer_gb(1:nvars)= (/time_io,                                         &
              vela_adv_x,vela_adv_y,vela_adv_z,vela_dif_x,vela_dif_y,vela_dif_z,       &
              vela_mig_x,vela_mig_y,vela_mig_z,vela_tot_x,vela_tot_y,vela_tot_z,       &
              ifrt_vx_adv_accu(ic,igb),ifrt_vy_adv_accu(ic,igb),ifrt_vz_adv_accu(ic,igb), &
              ifrt_vx_dif_accu(ic,igb),ifrt_vy_dif_accu(ic,igb),ifrt_vz_dif_accu(ic,igb), &
              ifrt_vx_mig_accu(ic,igb),ifrt_vy_mig_accu(ic,igb),ifrt_vz_mig_accu(ic,igb), &
              ifrt_vx_tot_accu(ic,igb),ifrt_vy_tot_accu(ic,igb),ifrt_vz_tot_accu(ic,igb)/)
            
            call binary_write_data(ifrt(ic,igb), 1, (/ngb_tstep/),     &
                        offset_ifrt_ijk(ic,igb),.true.)
            call binary_write_data(ifrt(ic,igb), nvars, realbuffer_gb, &
                        offset_ifrt(ic,igb),.true.) 
          
            offset_ifrt(ic,igb) = offset_ifrt(ic,igb) + nvars*nfloatbit
          else
  
            if (mtime == mtime_append .and. i_append_sim >= 1) then
              call reposition_file(ifrt(ic,igb),irecord)
  
              if (irecord > 0) then
                !c locate to the restart time and get previous results
                call reposition_file(ifrt(ic,igb),irecord,time_io_rs)
                read(ifrt(ic,igb),*,end=10,err=10) rdummys(1:nvars)
                !c reposition to the line to append results
                call reposition_file(ifrt(ic,igb),irecord)
  
                !c get the last record and add to the current value for accumulative results
                ifrt_vx_adv_accu(ic,igb) = ifrt_vx_adv_accu(ic,igb) + rdummys(14)
                ifrt_vy_adv_accu(ic,igb) = ifrt_vy_adv_accu(ic,igb) + rdummys(15)
                ifrt_vz_adv_accu(ic,igb) = ifrt_vz_adv_accu(ic,igb) + rdummys(16)
                ifrt_vx_dif_accu(ic,igb) = ifrt_vx_dif_accu(ic,igb) + rdummys(17)
                ifrt_vy_dif_accu(ic,igb) = ifrt_vy_dif_accu(ic,igb) + rdummys(18)
                ifrt_vz_dif_accu(ic,igb) = ifrt_vz_dif_accu(ic,igb) + rdummys(19)
                ifrt_vx_mig_accu(ic,igb) = ifrt_vx_mig_accu(ic,igb) + rdummys(20)
                ifrt_vy_mig_accu(ic,igb) = ifrt_vy_mig_accu(ic,igb) + rdummys(21)
                ifrt_vz_mig_accu(ic,igb) = ifrt_vz_mig_accu(ic,igb) + rdummys(22)
                ifrt_vx_tot_accu(ic,igb) = ifrt_vx_tot_accu(ic,igb) + rdummys(23)
                ifrt_vy_tot_accu(ic,igb) = ifrt_vy_tot_accu(ic,igb) + rdummys(24)
                ifrt_vz_tot_accu(ic,igb) = ifrt_vz_tot_accu(ic,igb) + rdummys(25)
              end if
10            continue
            end if
  
            if (i_append_sim < 1 .or.                                                    &
               (mtime >= mtime_append .and. i_append_sim >= 1)) then
              write(ifrt(ic,igb),ascii_fmt) time_io,                                   &
                vela_adv_x,vela_adv_y,vela_adv_z,vela_dif_x,vela_dif_y,vela_dif_z,       &
                vela_mig_x,vela_mig_y,vela_mig_z,vela_tot_x,vela_tot_y,vela_tot_z,       &
                ifrt_vx_adv_accu(ic,igb),ifrt_vy_adv_accu(ic,igb),ifrt_vz_adv_accu(ic,igb), &
                ifrt_vx_dif_accu(ic,igb),ifrt_vy_dif_accu(ic,igb),ifrt_vz_dif_accu(ic,igb), &
                ifrt_vx_mig_accu(ic,igb),ifrt_vy_mig_accu(ic,igb),ifrt_vz_mig_accu(ic,igb), &
                ifrt_vx_tot_accu(ic,igb),ifrt_vy_tot_accu(ic,igb),ifrt_vz_tot_accu(ic,igb)
            end if  
          end if
        end if

      end do
         
      return
      end subroutine tprfrtlc_faceflux
