!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 826 $
!> $Author: dsu $
!> $Date: 2022-03-24 10:10:16 -0700 (Thu, 24 Mar 2022) $
!> $URL: https://min3psvn.ubc.ca/svn/min3p_thcm/branches/dsu_new_add_2024Jan/src/dgm/ms_fluxdg.F90 $
!---------------------------------------------------------------------
!********************************************************************!
    
!c ----------------------------------------------------------------------
!c subroutine ms_fluxdg
!c --------------------------
!c
!c compute total diffusive flux of gases using the maxwell stefan equations
!c LU decomp of system matrix to calculate derivatives for global jacobian
!c
!c amat fmat  = bmat
!c
!c amat (i,i) = - SUM (Xj/Dij)
!c amat (i,j) =   Xi/Dij
!c bmat (i)   =   nabla(Ci)
!c fmat (i)   =   Ni^D  (molar diffusive flux of species i)
!c
!c equations for i=1 to ng-1 , i=ng replaced by equimolar or non-eq constraint
!c
!c written by:      Sergi Molins - May 2,2006
!c
!c last modified:   Sergi Molins - May 24,2006
!c                  press+temp dependence of diff coeff
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           c_i(ng)            = gaseous species concentrations      + -
!c                                at control volume i
!c           c_j(ng)            = gaseous species concentrations      + -
!c                                at control volume j
!c           c_ij(ng)           = gaseous species concentrations      + -
!c                                at interface i-j
!c           molfrac(ng)        = gas molar fraction at interface i   + -
!c           zgi                = elevation at control volume i       + -
!c           zgj                = elevation at control volume j       + -
!c           dens               = gas density at interface i-j        + -
!c           gpij               = gas pressure at interface i-j       + -
!c           tempkel            = temperature at interface i-j [K]    + -
!c           tauijx             = gas tortuosity at interface i-j     + -
!c           gporx              = porosity at interface i-j           + -
!c           delta_ijx          = distance between nodes i - j [m]    + -
!c           small              = constant                            + -
!c           ludecomp(ng,ng)    = matrix (see above)                  + -
!c           fmat(ng)           = molar diffusive fluxes for          + -
!c                                gas species [moles m^-2 d^-1]
!c           ms_gflux(nc)       = total molar diffusive fluxes for    * +
!c                                gas components [moles m^-2 d^-1]
!c           ms_neflux(nc)      = non-equimolar diffusive fluxes for  * +
!c                                gas components [moles m^-2 d^-1]
!c
!c           integer*4:
!c           ----------
!c           ipvt(ng)           = pivot indeces
!c                                (see dgefam.f,dgeslm.f subroutines) + -
!c
!c           logical:
!c           --------
!c           equimolar          = .true. -> equimolar diffusion       + -
!c
!c gen.f:    real*8:
!c           -------
!c           gacc               = gravity m s^-2                      + -
!c
!c           logical:
!c           -------
!c           gas_gravity        = enable gas gravity in advection     + -
!c
!c chem.f    real*8:
!c           -------
!c           rgasjoule          = ideal gas constant
!c                                [J/(deg K mol)]
!c           gfwg(ng)           = gram formula weight gas species     + -
!c           xnug(ng*nc)        = stoichiometric coefficient matrix 
!c                                for formation of gases from
!c                                components
!c           pa_atm             = pascal to atmosphere                + -
!c
!c           integer*4:
!c           ----------
!c           nc                 = number of components including h2o  + -
!c           ng                 = number of gas species               + -
!c           nr                 = number of redox couples             + -
!c           iaga(ng+1)         = row pointer array to                + -
!c                                stoichiometric coefficients of 
!c                                components in gases
!c           jaga(ng*nc)        = column pointer array to             + -
!c                                stoichiometric coefficients of 
!c                                components in gases
!c           logical:
!c           -------
!c           redox_equil        = .true.  -> equilibrium reactions    + -
!c                                           for redox couples
!c
!c phys.f:   real*8:
!c           -------
!c           diff_bin_g(ng,ng)  = binary diffusion coefficients       + -
!c           theta_diff         = exponent for temp correction        + -
!c
!c           logical:
!c           --------
!c           diff_press         = correction for pressure dependence  + -
!c           diff_temp          = correction for temp dependence      + -
!c
!c common:   -
!c
!c local:    real*8:
!c           -------
!c           r0               = constant
!c           r1               = constant
!c           neflux           = non-equimolar flux
!c           alpha_diff       = factor that modifies the diffusion coeff
!c                              as a function pressure and temperature
!c
!c           integer*4:
!c           ----------
!c           i                = index
!c           ic               = index
!c           jc               = index
!c           ig               = index
!c           istart           = index 
!c           iend             = index
!c
!c external: dgeslm.f         = linear system solver  
!c           dgefam.f         = LU decomp of linear system
!c           comptotc.f       = total gaseous component diff flux vectors
!c ----------------------------------------------------------------------
 
      subroutine  ms_fluxdg(c_i       ,c_j        ,                    &
     &                      c_ij      ,molfrac    ,                    &
     &                      zgi       ,zgj        ,                    &
     &                      dens      ,gpij       ,                    &
     &                      tempkel   ,tauijx     ,                    &
     &                      gporx     ,delta_ijx  ,                    &
     &                      small     ,                                &
     &                      ludecomp  ,fmat       ,                    &
     &                      ipvt      ,equimolar  ,                    &
     &                      ms_gflux  ,ms_neflux  )
 
        use gen, only  : gas_gravity, gacc
        use chem, only : gfwg, iaga, jaga, nc, ng, nr, pa_atm,         &
                         rgasjoule, redox_equil, xnug
        use phys, only : diff_bin_g, diff_press, diff_temp, theta_diff
        
        
        implicit none

!c------------------------------------------------
!c     constants
        real*8, parameter :: r0 = 0.0d0, r1 = 1.0d0,                   &
                             rverysmall = 1.0d-30                      
                                                                       
!c     passed                                                          
        real*8 ::    c_i(ng)         ,c_j(ng)        ,                 &
     &               c_ij(ng)        ,molfrac(ng)    ,                 &
     &               zgi             ,zgj            ,                 &
     &               dens            ,gpij           ,                 &
     &               tempkel         ,tauijx         ,                 &
     &               gporx           ,delta_ijx      ,                 &
     &               small           ,                                 &
     &               ludecomp(ng,ng) ,fmat(ng)       ,                 &
     &               ms_gflux(nc)    ,ms_neflux(nc)           

      integer*4 :: ipvt(ng)
      
      logical   :: equimolar

!c     internal
      integer*4 :: i, j, ic, ig, info, jc, jg, istart, iend

      real*8    :: bmat(ng-1)   ,amat(ng-1,ng-1),                     &
     &             neflux       ,                                     &
     &             beta(ng)     ,                                     &
     &             alpha_diff

!c--------------------------------------------------------------------------- 
!c     initialize variables
      do ic=1,ng-1
        amat(ic,ic)= r0
      enddo

!c     pressure & temperature dependence
      alpha_diff = r1

      if (diff_press) then      
        alpha_diff = alpha_diff / gpij / pa_atm         
      endif

      if (diff_temp) then      
        alpha_diff = alpha_diff * tempkel**theta_diff      
      endif

!c---------------------------------------------------------------------------
!c     check if there is gas phase
      if (gporx.lt.small) then
!c       no gas phase: do not calculate fluxes

      else
!c---------------------------------------------------------------------------
!c       set up Maxwell Stefan system
!c       right hand side vector      
        if (.not.gas_gravity) then ! do not include gravity
      
          do ic=1,ng-1
            bmat(ic) = (c_j(ic) - c_i(ic)) / delta_ijx
          enddo

        else                       ! include gravity
      
          do ic=1,ng-1
            bmat(ic) = (c_j(ic) - c_i(ic)) / delta_ijx                 &
     &                 +  dens * gacc * molfrac(ic) * (zgj - zgi)      &
     &                 /  delta_ijx / rgasjoule / tempkel / 1.d3
          enddo 

        endif

!c       initialize weight coefficients
        if (equimolar) then
        
          do jc=1,ng
            beta(jc) = 1.d0
          enddo
      
        else if (.not.equimolar) then

          do jc=1,ng
            beta(jc) = dsqrt(gfwg(jc))
          enddo

        endif
      
!c       Stefan-Maxwell system matrix
        do ic=1,ng-1
          
          do jc =1,ng-1
          
            if (ic.ne.jc) then
          
!c            --diagonal terms
              amat(ic,ic) = amat(ic,ic)                                &
     &                    - molfrac(jc)                                &
     &                    / diff_bin_g(ic,jc) / gporx / tauijx         &
     &                    / alpha_diff
          
!c            --off-diagonal terms
              amat(ic,jc) = 0.d0                                       &
     &                    + molfrac(ic)                                &
     &                    / diff_bin_g(ic,jc) / gporx / tauijx         &
     &                    / alpha_diff                                 &
     &                    - beta(jc) / beta(ng) * molfrac(ic)          &
     &                    / diff_bin_g(ic,ng) / gporx / tauijx         &  !ng-th gas sps
     &                    / alpha_diff
          
            endif !ic.ne.jc
          
          enddo ! jc
          
          amat(ic,ic) = amat(ic,ic)                                    &
     &                - molfrac(ng)                                    &
     &                / diff_bin_g(ic,ng) / gporx / tauijx             &
     &                / alpha_diff                                     &
     &                - beta(ic) / beta(ng) * molfrac(ic)              &
     &                / diff_bin_g(ic,ng) / gporx / tauijx             &  !ng-th gas species 
     &                / alpha_diff

        enddo ! ic

!c---------------------------------------------------------------------------
!c       solve for fluxes
!c       LU decomposition
        call dgefam (amat,ng-1,ng-1,ipvt,info)

!c       back substitution
        call dgeslm (amat,ng-1,ng-1,ipvt,bmat)
!c---------------------------------------------------------------------------

      endif ! calculation of fluxes
!c---------------------------------------------------------------------------

!c     calculate flux of ng-th gas species
!c     and store fluxes/matrix for derivatives
      fmat(ng) = r0
      
      do ig=1,ng-1
      
        fmat(ng) = fmat(ng) - beta(ig)/beta(ng) * bmat(ig)
        fmat(ig) = bmat(ig)
        do jg=1,ng-1
          ludecomp(ig,jg) = amat(ig,jg)
        enddo
      
      enddo

!c     calculate non-equimolar flux
      neflux = r0
      do ig=1,ng
        neflux = neflux + fmat(ig)
      enddo

!c     pass results to external variables
!c     initialize ms_gflux
      do ic=1,nc 
        ms_gflux(ic) = r0
        ms_neflux(ic) =r0
      enddo

      do ig=1,ng

        istart = iaga(ig)
        iend = iaga(ig+1)-1
    
        do i = istart,iend        
          ic = jaga(i)
          ms_gflux(ic)  = ms_gflux(ic) + fmat(ig) * xnug(i)
          ms_neflux(ic) = ms_neflux(ic) + neflux * molfrac(ig) * xnug(i)
        end do
        
      enddo

!c  compress total gaseous component diffusive flux vectors
!c  in case of redox equilibrium reactions

      if (redox_equil.and.nr.gt.0) then
        call comptotc(ms_gflux)
        call comptotc(ms_neflux)
      end if
!c---------------------------------------------------------------------------  
         
      return
      end